---
title: "Factor Analysis & Sim Data -- Iterate"
author: "Lizzy Gibson"
date: "3/5/2020"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
options(scipen = 999)
library(MNdata) # my data
library(reshape2) # melt
library(gridExtra) # gridarrange
library(bindata) # multivariate binomial dist
library(NMF) # rmatrix
library(MASS) # mvrnorm
library(tidyverse)
library(R.matlab)
library(psych)
```

## Load Sims

```{r}
load("./Sims/Iterate/sim_dist.RDA")
sim_dist

load("./Sims/Iterate/sim_cor.RDA")
sim_cor

load("./Sims/Iterate/sim_over.RDA")
sim_over
```

## Factor Analysis

### Distinct Patterns

```{r}
get_loadings <- function (sim) {
  loadings <- matrix(factanal(sim, 4, rotation="promax")$loadings, ncol = 4)
  colnames(loadings) <- c("f1", "f2", "f3", "f4")
  loadings
}

get_pred <- function (sim) {
  factanal(sim, 4, scores = "regression", rotation="promax")$scores %*% 
    t(matrix(factanal(sim, 4, rotation="promax")$loadings, ncol = 4))
}

fa_out_dist <- sim_dist %>% 
  mutate(loadings = map(sim, ~get_loadings(.x)),
         pred = map(sim, ~get_pred(.x)))

fa_out_dist$loadings[[1]]

fa_loadings_dist <- fa_out_dist %>% select(seed, loadings) %>% 
  mutate(F1 = map(loadings, ~.[,1]),
         F2 = map(loadings, ~.[,2]),
         F3 = map(loadings, ~.[,3]),
         F4 = map(loadings, ~.[,4])) %>% 
  unnest(F1:F4)

labels <-  c("pcb28", "pcb66", "pcb74", "pcb99", "pcb105", "pcb118", "pcb138_158", "pcb146", "pcb153", "pcb156", "pcb167",
          "pcb170", "pcb178", "pcb183", "pcb187", "pcb180", "pcb189", "pcb194", "pcb196_203", "pcb199", "pcb206", "pcb209",
          "BDE17", "BDE28", "BDE47", "BDE66", "BDE85", "BDE99", "BDE100", "BDE153", "BDE154", "BDE183", "BDE209", "MECPP",
          "MEHHP", "MEOHP", "MCPP", "MIBP", "MBP", "MBZP", "MEP", "MEHP", "dcp_24", "dcp_25", "b_pb", "bp_3", "m_pb",
          "p_pb", "tcs", "bpa")
```

#### Norm

```{r}
fa_out_dist %>%
  mutate(norm_all = map2(sim, pred, ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary()
```

#### Viz

```{r}
fa_loadings_dist %>%  
  filter(seed == 1) %>% 
  mutate(Chemicals = labels) %>% 
  select(seed, Chemicals, F1:F4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

fa_loadings_dist %>%  
  mutate(Chemicals = rep(labels, 100)) %>% 
  select(seed, Chemicals, F1:F4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = .45, outlier.shape = NA) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

```{r}
fa_loadings_dist %>%  
  mutate(Chemicals = rep(labels, 100)) %>% 
  select(seed, Chemicals, F1:F4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  group_by(Chemicals, Factor) %>% 
  summarise(med = median(Loadings),
            upper = quantile(Loadings, 0.75),
            lower = quantile(Loadings, 0.25)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = med)) + 
  geom_pointrange(aes(color = Group, min = lower, max = upper), alpha = 0.75, size = 0.25) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())
```

### Overlapping Patterns

```{r}
fa_out_over <- sim_over %>% 
  mutate(loadings = map(sim, ~get_loadings(.x)),
         pred = map(sim, ~get_pred(.x)))

fa_loadings_over <- fa_out_over %>% select(seed, loadings) %>% 
  mutate(F1 = map(loadings, ~.[,1]),
         F2 = map(loadings, ~.[,2]),
         F3 = map(loadings, ~.[,3]),
         F4 = map(loadings, ~.[,4])) %>% 
  unnest(F1:F4)
```

#### Norm

```{r}
fa_out_over %>%
  mutate(norm_all = map2(sim, pred, ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary()
```

#### Viz

```{r}
fa_loadings_over %>%  
  filter(seed == 7) %>% 
  mutate(Chemicals = labels) %>% 
  select(seed, Chemicals, F1:F4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

fa_loadings_over %>%  
  mutate(Chemicals = rep(labels, 100)) %>% 
  select(seed, Chemicals, F1:F4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = .45, outlier.shape = NA) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

```{r}
fa_loadings_over %>%  
  mutate(Chemicals = rep(labels, 100)) %>% 
  select(seed, Chemicals, F1:F4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  group_by(Chemicals, Factor) %>% 
  summarise(med = median(Loadings),
            upper = quantile(Loadings, 0.75),
            lower = quantile(Loadings, 0.25)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = med)) + 
  geom_pointrange(aes(color = Group, min = lower, max = upper), alpha = 0.75, size = 0.25) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())
```

### Correlated  Scores

```{r}
fa_out_cor <- sim_cor %>% 
  mutate(loadings = map(sim, ~get_loadings(.x)),
         pred = map(sim, ~get_pred(.x)))

fa_loadings_cor <- fa_out_cor %>% select(seed, loadings) %>% 
  mutate(F1 = map(loadings, ~.[,1]),
         F2 = map(loadings, ~.[,2]),
         F3 = map(loadings, ~.[,3]),
         F4 = map(loadings, ~.[,4])) %>% 
  unnest(F1:F4)
```

#### Norm

```{r}
fa_out_cor %>%
  mutate(norm_all = map2(sim, pred, ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary()
```

#### Viz

```{r}
fa_loadings_cor %>%  
  filter(seed == 7) %>% 
  mutate(Chemicals = labels) %>% 
  select(seed, Chemicals, F1:F4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

fa_loadings_cor %>%  
  mutate(Chemicals = rep(labels, 100)) %>% 
  select(seed, Chemicals, F1:F4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = .45, outlier.shape = NA) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

```{r}
fa_loadings_cor %>%  
  mutate(Chemicals = rep(labels, 100)) %>% 
  select(seed, Chemicals, F1:F4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  group_by(Chemicals, Factor) %>% 
  summarise(med = median(Loadings),
            upper = quantile(Loadings, 0.75),
            lower = quantile(Loadings, 0.25)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = med)) + 
  geom_pointrange(aes(color = Group, min = lower, max = upper), alpha = 0.75, size = 0.25) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())
```
