---
title: "PCA & Sim Data -- Iterate"
author: "Lizzy Gibson"
date: "2/26/2020"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
options(scipen = 999)
library(MNdata) # my data
library(reshape2) # melt
library(gridExtra) # gridarrange
library(bindata) # multivariate binomial dist
library(NMF) # rmatrix
library(MASS) # mvrnorm
library(tidyverse)
library(R.matlab)
```

## Load Sims

```{r}
load("./Sims/Iterate/sim_dist.RDA")
sim_dist

load("./Sims/Iterate/sim_cor.RDA")
sim_cor

load("./Sims/Iterate/sim_over.RDA")
sim_over
```

## PCA

### Distinct Patterns

```{r}
labels <-  c("pcb28", "pcb66", "pcb74", "pcb99", "pcb105", "pcb118", "pcb138_158", "pcb146", "pcb153", "pcb156", "pcb167",
          "pcb170", "pcb178", "pcb183", "pcb187", "pcb180", "pcb189", "pcb194", "pcb196_203", "pcb199", "pcb206", "pcb209",
          "BDE17", "BDE28", "BDE47", "BDE66", "BDE85", "BDE99", "BDE100", "BDE153", "BDE154", "BDE183", "BDE209", "MECPP",
          "MEHHP", "MEOHP", "MCPP", "MIBP", "MBP", "MBZP", "MEP", "MEHP", "dcp_24", "dcp_25", "b_pb", "bp_3", "m_pb",
          "p_pb", "tcs", "bpa")

get_rotations <- function (sim) {
  as_tibble(prcomp(sim_dist$sim[[1]])$rotation[,1:4])
}

get_x <- function (sim) {
  as_tibble(prcomp(sim)$x)
}

get_pred <- function (sim) {
  svd(sim)$u[,1:4] %*% diag(svd(sim)$d[1:4]) %*% t(svd(sim)$v[,1:4])
}

pca_out_dist <- sim_dist %>% 
  mutate(rotations = map(sim, ~get_rotations(.x)),
         ex = map(sim, ~get_x(.x)),
         pred = map(sim, ~get_pred(.x)))

pca_rotations_dist <- pca_out_dist %>% select(seed, rotations) %>% unnest(cols = c(rotations))
```

#### Norms

```{r}
# All
pca_out_dist %>%
  mutate(norm_all = map2(sim, pred, ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary()

pca_reorder_dist <- pca_rotations_dist %>%  
  mutate(Chemicals = rep(labels, 100)) %>% 
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  group_by(PC, seed) %>%
  mutate(Loadings = case_when(
    any(PC == "PC1" & Chemicals == "pcb28" & Loadings < 0) ~ -Loadings,
    any(PC == "PC2" & Chemicals == "MEP" & Loadings < 0) ~ -Loadings,
    any(PC == "PC3" & Chemicals == "bpa" & Loadings < 0) ~ -Loadings,
    any(PC == "PC4" & Chemicals == "BDE99" & Loadings < 0) ~ -Loadings,
    TRUE ~ Loadings
  )) %>%
  spread(PC, Loadings)
  
# Loadings (reordered, not scaled)
pca_reorder_dist %>%
  select(-Chemicals) %>% 
  nest(reorder_loadings = PC1:PC4) %>% 
  left_join(., pca_out_dist, by = "seed") %>% 
  select(seed, patterns, rotations) %>% 
  mutate(norm_rotations = map2(patterns, rotations, ~norm(as.matrix(.x) - as.matrix(t(.y)), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_rotations) %>% 
  pull(norm_rotations) %>% summary()
```

#### Viz

```{r}
pca_rotations_dist %>%  
  filter(seed == 1) %>% 
  mutate(Chemicals = labels) %>% 
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
    group_by(PC, seed) %>%
  mutate(Loadings = case_when(
    any(PC == "PC1" & Chemicals == "pcb28" & Loadings < 0) ~ -Loadings,
    any(PC == "PC2" & Chemicals == "MEP" & Loadings < 0) ~ -Loadings,
    any(PC == "PC3" & Chemicals == "bpa" & Loadings < 0) ~ -Loadings,
    any(PC == "PC4" & Chemicals == "BDE99" & Loadings < 0) ~ -Loadings,
    TRUE ~ Loadings # These dont change plot at all, should be able to standardize all 100 sims
  )) %>%
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~PC) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

pca_reorder_dist %>%  
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = 0.4, outlier.shape = NA) +
  facet_wrap(.~PC) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

```{r}
pca_reorder_dist %>%  
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  group_by(Chemicals, PC) %>% 
  summarise(med = median(Loadings),
            upper = quantile(Loadings, 0.75),
            lower = quantile(Loadings, 0.25)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = med)) + 
  geom_pointrange(aes(color = Group, min = lower, max = upper), alpha = 0.75, size = 0.25) +
  facet_wrap(.~PC) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())
```

### Overlapping Patterns

```{r}
pca_out_over <- sim_over %>% 
  mutate(rotations = map(sim, ~get_rotations(.x)),
         ex = map(sim, ~get_x(.x)),
         pred = map(sim, ~get_pred(.x)))

pca_rotations_over <- pca_out_over %>% select(seed, rotations) %>% unnest(cols = c(rotations))
```

#### Norm

```{r}
# All
pca_out_over %>%
  mutate(norm_all = map2(sim, pred, ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary()

pca_reorder_over <- pca_rotations_over %>%  
  mutate(Chemicals = rep(labels, 100)) %>% 
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  group_by(PC, seed) %>%
  mutate(Loadings = case_when(
    any(PC == "PC1" & Chemicals == "pcb28" & Loadings < 0) ~ -Loadings,
    any(PC == "PC2" & Chemicals == "MEP" & Loadings < 0) ~ -Loadings,
    any(PC == "PC3" & Chemicals == "bpa" & Loadings < 0) ~ -Loadings,
    any(PC == "PC4" & Chemicals == "BDE99" & Loadings < 0) ~ -Loadings,
    TRUE ~ Loadings
  )) %>%
  spread(PC, Loadings)
  
# Loadings (reordered, not scaled)
pca_reorder_over %>%
  select(-Chemicals) %>% 
  nest(reorder_loadings = PC1:PC4) %>% 
  left_join(., pca_out_dist, by = "seed") %>% 
  select(seed, patterns, rotations) %>% 
  mutate(norm_rotations = map2(patterns, rotations, ~norm(as.matrix(.x) - as.matrix(t(.y)), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_rotations) %>% 
  pull(norm_rotations) %>% summary()
```

#### Viz

```{r}
pca_rotations_over %>%  
  filter(seed == 7) %>% 
  mutate(Chemicals = labels) %>% 
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~PC) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

pca_reorder_over %>%  
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = 0.4, outlier.shape = NA) +
  facet_wrap(.~PC) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

```{r}
pca_reorder_over %>%  
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  group_by(Chemicals, PC) %>% 
  summarise(med = median(Loadings),
            upper = quantile(Loadings, 0.75),
            lower = quantile(Loadings, 0.25)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = med)) + 
  geom_pointrange(aes(color = Group, min = lower, max = upper), alpha = 0.75, size = 0.25) +
  facet_wrap(.~PC) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())
```

### Correlated  Scores

```{r}
pca_out_cor <- sim_cor %>% 
  mutate(rotations = map(sim, ~get_rotations(.x)),
         ex = map(sim, ~get_x(.x)),
         pred = map(sim, ~get_pred(.x)))

pca_rotations_cor <- pca_out_cor %>% select(seed, rotations) %>% unnest(cols = c(rotations))
```

#### Norm

```{r}
# All
pca_out_cor %>%
  mutate(norm_all = map2(sim, pred, ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary()

pca_reorder_cor <- pca_rotations_cor %>%  
  mutate(Chemicals = rep(labels, 100)) %>% 
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  group_by(PC, seed) %>%
  mutate(Loadings = case_when(
    any(PC == "PC1" & Chemicals == "pcb28" & Loadings < 0) ~ -Loadings,
    any(PC == "PC2" & Chemicals == "MEP" & Loadings < 0) ~ -Loadings,
    any(PC == "PC3" & Chemicals == "bpa" & Loadings < 0) ~ -Loadings,
    any(PC == "PC4" & Chemicals == "BDE99" & Loadings < 0) ~ -Loadings,
    TRUE ~ Loadings
  )) %>%
  spread(PC, Loadings)
  
# Loadings (reordered, not scaled)
pca_reorder_cor %>%
  select(-Chemicals) %>% 
  nest(reorder_loadings = PC1:PC4) %>% 
  left_join(., pca_out_dist, by = "seed") %>% 
  select(seed, patterns, rotations) %>% 
  mutate(norm_rotations = map2(patterns, rotations, ~norm(as.matrix(.x) - as.matrix(t(.y)), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_rotations) %>% 
  pull(norm_rotations) %>% summary()
```

#### Viz

```{r}
pca_rotations_cor %>%  
  filter(seed == 7) %>% 
  mutate(Chemicals = labels) %>% 
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~PC) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

pca_reorder_cor %>%  
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = 0.4, outlier.shape = NA) +
  facet_wrap(.~PC) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

```{r}
pca_reorder_cor %>%  
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  group_by(Chemicals, PC) %>% 
  summarise(med = median(Loadings),
            upper = quantile(Loadings, 0.75),
            lower = quantile(Loadings, 0.25)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = med)) + 
  geom_pointrange(aes(color = Group, min = lower, max = upper), alpha = 0.75, size = 0.25) +
  facet_wrap(.~PC) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())
```

## Standardize

```{r}
standardize <- function (any_matrix) {
  apply(any_matrix, 2, function(x) x/sd(x))
  }
  
dist_norm <- pca_reorder_dist %>% 
  select(-Chemicals) %>% 
  nest(reorder = PC1:PC4) %>% 
  left_join(., pca_out_dist, by = "seed") %>% 
  mutate(sd_patterns = map(patterns, ~standardize(.x)),
         sd_rotations = map(reorder, ~standardize(t(.x)))) %>% 
  mutate(norm_rotations = map2(sd_patterns, sd_rotations, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_rotations) %>% 
  pull(norm_rotations)

over_norm <- pca_reorder_over %>% 
  select(-Chemicals) %>% 
  nest(reorder = PC1:PC4) %>% 
  left_join(., pca_out_over, by = "seed") %>% 
  mutate(sd_patterns = map(patterns, ~standardize(.x)),
         sd_rotations = map(reorder, ~standardize(t(.x)))) %>% 
  mutate(norm_rotations = map2(sd_patterns, sd_rotations, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_rotations) %>% 
  pull(norm_rotations)
  
cor_norm <- pca_reorder_cor %>% 
  select(-Chemicals) %>% 
  nest(reorder = PC1:PC4) %>% 
  left_join(., pca_out_cor, by = "seed") %>% 
  mutate(sd_patterns = map(patterns, ~standardize(.x)),
         sd_rotations = map(reorder, ~standardize(t(.x)))) %>% 
  mutate(norm_rotations = map2(sd_patterns, sd_rotations, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_rotations) %>% 
  pull(norm_rotations) 

summary(over_norm)
summary(cor_norm)
summary(dist_norm)
(sum(dist_norm) + sum(cor_norm) + sum(over_norm)) / 300
```
