---
title: "Test NMF on Sims"
author: "Lizzy Gibson"
date: "7/24/2019"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
options(scipen = 999)
library(MNdata) # my data
library(reshape2) # melt
library(gridExtra) # gridarrange
library(bindata) # multivariate binomial dist
library(NMF) # rmatrix
library(MASS) # mvrnorm
library(tidyverse)
```

## Read in Sims

```{r}
sim1 <- read_csv("sim_data_1.csv")
sim2 <- read_csv("sim_data_2.csv")
sim3 <- read_csv("sim_data_3.csv")
```

## NMF Function

```{r}
# % NMF implements non-negative matrix factorization of the matrix X
# % according to a predefined penalty.

# % X : D x N matrix of nonnegative numbers
# % K : rank of factorization, takes value in {1,2,3,...,min(D,N)}
# % penalty : string taking one of two values, 'L2' or 'divergence'
# % num_iter : number of iterations

nmf_ee <- function(X, K, penalty, num_iter) {

  X <- as.matrix(X)
  D <- nrow(X)
  N <- ncol(X)
  
  # Initiate W and H matrices with random non-zero values
  W <- matrix(1, nrow = D, ncol = K) + matrix(runif(D*K), nrow = D, ncol = K)
  H <- matrix(1, nrow = K, ncol = N) + matrix(runif(K*N), nrow = K, ncol = N)
  
  temp <- sum(X)/sum(W %*% H) 
  # temp is the magnitude of the original matrix divided by the matrix product of W and H
  # each iteration, this ratio should get closer to 1
  W <- W*sqrt(temp) 
  # new W is scaled by the magnitude of the ratio between the original X and the current W and H
  # each iteration, this W gets closer to the solution
  H <- H*sqrt(temp) 
  # new H is scaled by the magnitude of the ratio between the original X and the current W and H
  # each iteration, this H gets closer to the solution
  
  L <- matrix() # empty to fill in with loss function
  
  # Define 'eps'
  # 'eps' is the distance from 1.0 to the next larger double-precision floating point number, that is, 2-52.
  eps <- 2.2204e-16
  
  if (!(penalty %in% c('L2', 'divergence'))) {print('Invalid penalty input.')}
  
  # Iterate to minimize loss function
    else if (penalty == 'L2') {
      for (i in 1:num_iter) {
            H <- H * (t(W) %*% X) / ((t(W) %*% W) %*% H + eps) # eps prevents division by zero
            W <- W * (X %*% t(H)) / (W %*% (H %*% t(H)) + eps)
      # Loss function -- Gaussian MLE
      L[i] <- sum((X - W %*% H)^2)
      }
      return(list(ind_scores = W, chem_loadings = H, loss = L))
      }
  
    else if (penalty == 'divergence') {
      for (i in 1:num_iter) {
          H <- H * (t(W / kronecker(matrix(1,D,1), matrix(colSums(W), nrow=1))) %*% (X / (W %*% H + eps)))
          # kronecker creates a matrix of the column sums of W repeated row-stacked
          W <- W * ((X / (W %*% H + eps)) %*% t(H / kronecker(matrix(1,1,N), matrix(rowSums(H), ncol = 1))))
          # kronecker creates a matrix of the row sums of H repeated column-stacked
      # Loss function -- Poisson MLE
      L[i] <- (-sum(X * log(W %*% H))) + (sum(W %*% H))
      }
      return(list(ind_scores = W, chem_loadings = H, loss = L))
      }
  }
```

## Compare Results

### 10x10

```{r}
fake <- matrix(1:100, nrow = 10, byrow = TRUE)
fake

nmf_ee(fake, 4, "L2", 100)
# L2 results same when ones replace rand

nmf_ee(fake, 4, "divergence", 100)
# divergence results same when ones replace rand
```

## L2 Penalty

### Distinct Patterns

```{r}
sim1

results_dist <- nmf_ee(sim1, 4, "L2", 100)
```

```{r}
results_dist$chem_loadings %>% as_tibble() %>% 
  mutate(Pattern = 1:4) %>% select(Pattern, everything()) %>% 
  gather(key = Chemical, value = Loadings, -Pattern) %>% 
  mutate(Group = case_when(grepl("pcb", Chemical) ~ "PCBs",
                           grepl("BDE", Chemical) ~ "PBDEs",
                           grepl("^M", Chemical) ~ "PHTs",
                           grepl("p_|_p", Chemical) ~ "Phenols",
                           Chemical == "tcs" ~ "Phenols",
                           Chemical == "bpa" ~ "Phenols")) %>% 
  arrange(Group) %>% 
  mutate(Chemical = fct_inorder(Chemical)) %>% 
  ggplot(aes(x = Chemical, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Pattern) + theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom",
        strip.background = element_blank())
```

### Overlapping Patterns

```{r}
sim2

results_over <- nmf_ee(sim2, 4, "L2", 100)
```

```{r}
results_over$chem_loadings %>% as_tibble() %>% 
  mutate(Pattern = 1:4) %>% select(Pattern, everything()) %>% 
  gather(key = Chemical, value = Loadings, -Pattern) %>% 
  mutate(Group = case_when(grepl("pcb", Chemical) ~ "PCBs",
                           grepl("BDE", Chemical) ~ "PBDEs",
                           grepl("^M", Chemical) ~ "PHTs",
                           grepl("p_|_p", Chemical) ~ "Phenols",
                           Chemical == "tcs" ~ "Phenols",
                           Chemical == "bpa" ~ "Phenols")) %>% 
  arrange(Group) %>% 
  mutate(Chemical = fct_inorder(Chemical)) %>% 
  ggplot(aes(x = Chemical, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Pattern) + theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom",
        strip.background = element_blank())
```

### Correlated Patterns

```{r}
sim3

results_corr <- nmf_ee(sim3, 4, "L2", 100)
```

```{r}
results_corr$chem_loadings %>% as_tibble() %>% 
  mutate(Pattern = 1:4) %>% select(Pattern, everything()) %>% 
  gather(key = Chemical, value = Loadings, -Pattern) %>% 
  mutate(Group = case_when(grepl("pcb", Chemical) ~ "PCBs",
                           grepl("BDE", Chemical) ~ "PBDEs",
                           grepl("^M", Chemical) ~ "PHTs",
                           grepl("p_|_p", Chemical) ~ "Phenols",
                           Chemical == "tcs" ~ "Phenols",
                           Chemical == "bpa" ~ "Phenols")) %>% 
  arrange(Group) %>% 
  mutate(Chemical = fct_inorder(Chemical)) %>% 
  ggplot(aes(x = Chemical, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Pattern) + theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom",
        strip.background = element_blank())
```

## Poisson Penalty

### Distinct Patterns

```{r}
sim1

results_dist2 <- nmf_ee(sim1, 4, "divergence", 100)
```

```{r}
results_dist2$chem_loadings %>% as_tibble() %>% 
  mutate(Pattern = 1:4) %>% select(Pattern, everything()) %>% 
  gather(key = Chemical, value = Loadings, -Pattern) %>% 
  mutate(Group = case_when(grepl("pcb", Chemical) ~ "PCBs",
                           grepl("BDE", Chemical) ~ "PBDEs",
                           grepl("^M", Chemical) ~ "PHTs",
                           grepl("p_|_p", Chemical) ~ "Phenols",
                           Chemical == "tcs" ~ "Phenols",
                           Chemical == "bpa" ~ "Phenols")) %>% 
  arrange(Group) %>% 
  mutate(Chemical = fct_inorder(Chemical)) %>% 
  ggplot(aes(x = Chemical, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Pattern) + theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom",
        strip.background = element_blank())
```

### Overlapping Patterns

```{r}
sim2

results_over2 <- nmf_ee(sim2, 4, "divergence", 100)
```

```{r}
results_over2$chem_loadings %>% as_tibble() %>% 
  mutate(Pattern = 1:4) %>% select(Pattern, everything()) %>% 
  gather(key = Chemical, value = Loadings, -Pattern) %>% 
  mutate(Group = case_when(grepl("pcb", Chemical) ~ "PCBs",
                           grepl("BDE", Chemical) ~ "PBDEs",
                           grepl("^M", Chemical) ~ "PHTs",
                           grepl("p_|_p", Chemical) ~ "Phenols",
                           Chemical == "tcs" ~ "Phenols",
                           Chemical == "bpa" ~ "Phenols")) %>% 
  arrange(Group) %>% 
  mutate(Chemical = fct_inorder(Chemical)) %>% 
  ggplot(aes(x = Chemical, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Pattern) + theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom",
        strip.background = element_blank())
```

### Correlated Patterns

```{r}
sim3

results_corr2 <- nmf_ee(sim3, 4, "divergence", 100)
```

```{r}
results_corr2$chem_loadings %>% as_tibble() %>% 
  mutate(Pattern = 1:4) %>% select(Pattern, everything()) %>% 
  gather(key = Chemical, value = Loadings, -Pattern) %>% 
  mutate(Group = case_when(grepl("pcb", Chemical) ~ "PCBs",
                           grepl("BDE", Chemical) ~ "PBDEs",
                           grepl("^M", Chemical) ~ "PHTs",
                           grepl("p_|_p", Chemical) ~ "Phenols",
                           Chemical == "tcs" ~ "Phenols",
                           Chemical == "bpa" ~ "Phenols")) %>% 
  arrange(Group) %>% 
  mutate(Chemical = fct_inorder(Chemical)) %>% 
  ggplot(aes(x = Chemical, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Pattern) + theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom",
        strip.background = element_blank())
```

