%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/lizzy/OneDrive/Columbia/Spring 2020/nmf/Data/edc_cc_27.csv
%
% Auto-generated by MATLAB on 10-Mar-2020 08:44:26

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 27);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["BDE28", "BDE47", "BDE66", "BDE85", "BDE99", "BDE100", "BDE153", "BDE154", "BDE183", "BDE209", "MECPP_sg_adj", "MEHHP_sg_adj", "MEOHP_sg_adj", "MCPP_sg_adj", "MIBP_sg_adj", "MBP_sg_adj", "MBZP_sg_adj", "MEP_sg_adj", "MEHP_sg_adj", "dcp_24_sg_adj", "dcp_25_sg_adj", "b_pb_sg_adj", "bp_3_sg_adj", "m_pb_sg_adj", "p_pb_sg_adj", "tcs_sg_adj", "bpa_sg_adj"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
edccc27 = readtable("/Users/lizzy/OneDrive/Columbia/Spring 2020/nmf/Data/edc_cc_27.csv", opts);

%% Convert to output type
edccc27 = table2array(edccc27);

%% Clear temporary variables
clear opts

[ewa_cc,eh_cc] = NPBayesNMF(edccc27, 51, 10000);

labels = ["BDE28", "BDE47", "BDE66", "BDE85", "BDE99", "BDE100", "BDE153", ...
    "BDE154", "BDE183", "BDE209", "MECPP", "MEHHP", "MEOHP", "MCPP", "MIBP", "MBP", "MBZP", "MEP", "MEHP", ...
    "dcp_24", "dcp_25", "b_pb", "bp_3", "m_pb", "p_pb", "tcs", "bpa"];
       
%PLOT
figure;
subplot(3,1,1);
stem(eh_cc(1,:));
set(gca,'XTick',1:size(eh_cc,2));
set(gca,'XTickLabels',labels);
subplot(3,1,2);
stem(eh_cc(2,:));
set(gca,'XTick',1:size(eh_cc,2));
set(gca,'XTickLabels',labels);
subplot(3,1,3);
stem(eh_cc(3,:));
set(gca,'XTick',1:size(eh_cc,2));
set(gca,'XTickLabels',labels);

%save("/Users/lizzy/OneDrive/Columbia/Spring 2020/nmf/Sims/Iterate_Out/ewa_edc_cc.mat", 'ewa_cc');
%save("/Users/lizzy/OneDrive/Columbia/Spring 2020/nmf/Sims/Iterate_Out/eh_edc_cc.mat", 'eh_cc');
