%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/lizzy/OneDrive/Columbia/Spring 2020/nmf/Data/edc_all.csv
%
% Auto-generated by MATLAB on 06-Mar-2020 10:17:20

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 51);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["MECPP_sg_adj", "MEHHP_sg_adj", "MEOHP_sg_adj", "MCPP_sg_adj", "MIBP_sg_adj", "MBP_sg_adj", "MBZP_sg_adj", "MEP_sg_adj", "MEHP_sg_adj", "dcp_24_sg_adj", "dcp_25_sg_adj", "b_pb_sg_adj", "bp_3_sg_adj", "m_pb_sg_adj", "p_pb_sg_adj", "tcs_sg_adj", "bpa_sg_adj", "BDE28", "BDE47", "BDE66", "BDE85", "BDE99", "BDE100", "BDE153", "BDE154", "BDE183", "BDE209", "pcb28", "pcb66", "pcb74", "pcb99", "pcb105", "pcb114", "pcb118", "pcb138_158", "pcb146", "pcb153", "pcb156", "pcb157", "pcb167", "pcb170", "pcb178", "pcb180", "pcb183", "pcb187", "pcb189", "pcb194", "pcb196_203", "pcb199", "pcb206", "pcb209"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
edc_all = readtable("/Users/lizzy/OneDrive/Columbia/Spring 2020/nmf/Data/edc_all.csv", opts);
edc_all = rmmissing(edc_all)
%% Convert to output type
edc_all = table2array(edc_all);

%% Clear temporary variables
clear opts

[ewa_all,eh_all] = NPBayesNMF(edc_all, 51, 10000);

labels = ["pcb28", "pcb66", "pcb74", "pcb99", "pcb105", "pcb114", "pcb118", "pcb138_158" "pcb146", "pcb153", ...
    "pcb156", "pcb157", "pcb167", "pcb170", "pcb178", "pcb180", "pcb183", "pcb187", "pcb189", "pcb194", ...
    "pcb196_203" "pcb199", "pcb206", "pcb209", "BDE28", "BDE47", "BDE66", "BDE85", "BDE99", "BDE100", "BDE153", ...
    "BDE154", "BDE183", "BDE209", "MECPP", "MEHHP", "MEOHP", "MCPP", "MIBP", "MBP", "MBZP", "MEP", "MEHP", ...
    "dcp_24", "dcp_25", "b_pb", "bp_3", "m_pb", "p_pb", "tcs", "bpa"];
       
%PLOT
figure;
subplot(2,1,1);
stem(eh_all(1,:));
set(gca,'XTick',1:size(eh_all,2));
set(gca,'XTickLabels',labels);
subplot(2,1,2);
stem(eh_all(2,:));
set(gca,'XTick',1:size(eh_all,2));
set(gca,'XTickLabels',labels);

save("/Users/lizzy/OneDrive/Columbia/Spring 2020/nmf/Sims/Iterate_Out/ewa_edc_all.mat", 'ewa_all');
save("/Users/lizzy/OneDrive/Columbia/Spring 2020/nmf/Sims/Iterate_Out/eh_edc_all.mat", 'eh_all');
