%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/lizzy/Principle.Component.Pursuit/sim_nhanes_lod50.csv
%
% Auto-generated by MATLAB on 06-May-2020 15:40:55

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 18);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["PCB074", "PCB099", "PCB118", "PCB138", "PCB153", "PCB170", "PCB180", "PCB187", "D03", "D05", "D07", "F03", "F04", "F05", "F08", "PCBpcb", "PCBhxc", "PCB194"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
simnhaneslod50 = readtable("/Users/lizzy/Principle.Component.Pursuit/sim_nhanes_lod50.csv", opts);

%% Convert to output type
simnhaneslod50 = table2array(simnhaneslod50);

%% Clear temporary variables
clear opts

delta = [ 0.4891767  0.5575821  0.4050706  0.4024336  0.3590648  0.4796017  0.3553258 ...
    0.4873942  0.3763090  0.4742076  0.5490598  0.4671966  0.6399726  0.6241931  0.6171448 ...
    0.3827238  0.3745601  0.5360889 ]

[L, S] = pcp_lod(simnhaneslod50, 0.03162278, 0.9584064, delta)