%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/lizzy/nmf/R/Sims/Iterate/sim_over_100.csv
%
% Auto-generated by MATLAB on 24-Aug-2020 10:52:04

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 50);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["pcb28", "pcb66", "pcb74", "pcb99", "pcb105", "pcb118", "pcb138_158", "pcb146", "pcb153", "pcb156", "pcb167", "pcb170", "pcb178", "pcb183", "pcb187", "pcb180", "pcb189", "pcb194", "pcb196_203", "pcb199", "pcb206", "pcb209", "BDE17", "BDE28", "BDE47", "BDE66", "BDE85", "BDE99", "BDE100", "BDE153", "BDE154", "BDE183", "BDE209", "MECPP", "MEHHP", "MEOHP", "MCPP", "MIBP", "MBP", "MBZP", "MEP", "MEHP", "dcp_24", "dcp_25", "b_pb", "bp_3", "m_pb", "p_pb", "tcs", "bpa"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
simover100 = readtable("/Users/lizzy/nmf/R/Sims/Iterate/sim_over_100.csv", opts);


%% Clear temporary variables
clear opts

%% Convert to output type
simover100 = table2array(simover100);
%flip = isee2020dat'

% Calculate std for each column
% sd = std(simover100, [], 1); 
% Subtract mean and divide by std
% dataNorm = (simover100) ./ sd; 

%% Clear temporary variables
clear opts

[EWA, EH, EW, EA, varWA, varH, varW, alphaH, betaH] = NPBayesNMF(simover100, 50);

labels = ["pcb28", "pcb66", "pcb74", "pcb99", "pcb105", "pcb118", "pcb138_158", "pcb146", "pcb153", ...
    "pcb156", "pcb167", "pcb170", "pcb178", "pcb183", "pcb187", "pcb180", "pcb189", "pcb194", "pcb196_203", ...
    "pcb199", "pcb206", "pcb209", "BDE17", "BDE28", "BDE47", "BDE66", "BDE85", "BDE99", "BDE100", "BDE153", ...
    "BDE154", "BDE183", "BDE209", "MECPP", "MEHHP", "MEOHP", "MCPP", "MIBP", "MBP", "MBZP", "MEP", "MEHP", ...
    "dcp_24", "dcp_25", "b_pb", "bp_3", "m_pb", "p_pb", "tcs", "bpa"];

%PLOT
figure;
subplot(2,2,1);
stem(EH(1,:));
set(gca,'XTick',1:size(EH,2));
set(gca,'XTickLabels',labels);
subplot(2,2,2);
stem(EH(2,:));
set(gca,'XTick',1:size(EH,2));
set(gca,'XTickLabels',labels);
subplot(2,2,3);
stem(EH(3,:));
set(gca,'XTick',1:size(EH,2));
set(gca,'XTickLabels',labels);
subplot(2,2,4);
stem(EH(4,:));
set(gca,'XTick',1:size(EH,2));
set(gca,'XTickLabels',labels);

save("/Users/lizzy/nmf/MATLAB/Output/sim_over_100_ewa.mat", 'EWA');
save("/Users/lizzy/nmf/MATLAB/Output/sim_over_100_eh.mat", 'EH');
save("/Users/lizzy/nmf/MATLAB/Output/sim_over_100_varwa.mat", 'varWA');
save("/Users/lizzy/nmf/MATLAB/Output/sim_over_100_alphah.mat", 'alphaH');
save("/Users/lizzy/nmf/MATLAB/Output/sim_over_100_betah.mat", 'betaH');

