---
title: "Loop Simulations: Separable"
author: "Lizzy Gibson"
date: "2/17/2021"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
options(scipen = 999)

library(tidyverse)
library(GGally)
library(LearnBayes)
library(openssl)
```

## 1: Separate Patterns

### Simulate Patterns

```{r}
vec = as.integer(rand_num(100) * ((2^31)-1))
rand_vec = rep(vec, 3)

## Construct a matrix for 4 TRUE exposure patterns
create_patterns <- function (seed, reps) {
  set.seed(seed)
  pat1=c(0,0,5,10)
  pat2=c(0,5,10,0)
  pat3=c(5,10,0,0)
  pat4=c(10,0,0,5)
  
  start = c()
  for (i in 1:reps) {
    start = cbind(start,diag(1,4))
  }
  
  patterns = cbind(start, t(rdirichlet(13-reps, pat1)), t(rdirichlet(13-reps, pat2)),
                   t(rdirichlet(12-reps, pat3)), t(rdirichlet(12-reps, pat4)))
  return(patterns)
}

reps = c(rep(1, 100), rep(2, 100), rep(3, 100))

patterns_iter <- tibble(seed = rand_vec, reps, data = "Separate") %>% 
 mutate(true_patterns = map2(seed, reps, create_patterns))
```

### Simulate Scores
   
```{r}
create_scores <- function (seed) {
  set.seed(seed)
  scores <- matrix(exp(rnorm(1000*4)), ncol = 4)

  return(scores)
}

scores_iter <- patterns_iter %>% 
 mutate(true_scores = map(seed, create_scores))
```

### Simulate Chemical Exposures

* Matrix multiple scores and pattern loadings

```{r}
sim_iter <- scores_iter %>% 
  mutate(chem = map2(true_scores, true_patterns, `%*%`))
```

### Simulate Noise

* Add noise
* Noise distribution Normal(0, 1)
    
```{r}
add_noise <- function (seed, chemx) {
  n = nrow(chemx)
  p = ncol(chemx)
  noise <- matrix(rnorm(n*p, mean = 0, sd = 1), nrow = n, ncol = p)
  sim = pmax(chemx + noise, 0)
  return(sim)
}

sims <- sim_iter %>% 
 mutate(sim = map2(seed, chem, add_noise))
```  

```{r}
dist <- sims$sim[[1]]
ggcorr(dist)
```

## Save

```{r} 
sims
  
# for (i in 1:nrow(sims)) {
#   write_csv(as_tibble(sims$sim[[i]]),           paste0("./Sims/Sep/sim_sep_", i, ".csv"))
#   write_csv(as_tibble(sims$chem[[i]]),          paste0("./Sims/Sep/chem_sep_", i, ".csv"))
#   write_csv(as_tibble(sims$true_patterns[[i]]), paste0("./Sims/Sep/patterns_sep_", i, ".csv"))
#   write_csv(as_tibble(sims$true_scores[[i]]),   paste0("./Sims/Sep/scores_sep_", i, ".csv"))
# }

# save(sims, file = "./Sims/sim_sep.RDA")
```

