---
title: "ISEE"
author: "Lizzy Gibson"
date: "10/20/2020"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggsci)
library(GGally)
library(cowplot)

knitr::opts_chunk$set(
	echo = FALSE,
  warning = FALSE,
  message = FALSE,
	cache = TRUE,
	autodep=TRUE,
  fig.width = 8,
  fig.height = 6
)

knitr::dep_auto()

theme_set(theme_bw(base_size = 15) + 
            theme(legend.position = "bottom",
                  strip.background =element_rect(fill="white"),
                  axis.text.x = element_text(angle = 45, hjust = 1)))

ggsci <- pal_nejm()(8)

options(
  scipen = 999,
  ggplot2.discrete.colour = ggsci,
  ggplot2.discrete.fill = ggsci)
```

## Raw x Raw

```{r, loadraw, cache = TRUE, cache.lazy=FALSE}
load(file = here::here("./HPC/Rout/isee.RDA"))
# isee
```

```{r}
iseesim <- 
  isee %>% select(seed, data, sim) %>% 
  filter(seed == 1) %>% 
  mutate(sim = map(sim, as_tibble)) %>% 
  unnest(sim)
```

### Distributions

```{r plot6, fig.width = 8, fig.height = 2}
# Distinct
iseesim %>% 
  filter(data == "distinct") %>% 
  select(3:8) %>% 
  pivot_longer(1:5) %>% 
  ggplot(aes(x = value)) + 
  facet_wrap(. ~ name, scales = "free", nrow = 1) +
  geom_histogram(bins = 100) + 
  labs(x = "Distinct Simulations",
       y = "Count")
```

```{r plot7, fig.width = 8, fig.height = 2}
# Overlapping
iseesim %>% 
  filter(data == "overlapping") %>% 
  select(3:8) %>% 
  pivot_longer(1:5) %>% 
  ggplot(aes(x = value)) + 
  facet_wrap(. ~ name, scales = "free", nrow = 1) +
  geom_histogram(bins = 100) + 
  labs(x = "Overlapping Simulations",
       y = "Count")
```

#### Ranges

##### Distinct

* Means: (`r round(range(apply(as_tibble(isee$sim[[1]]), 2, mean)), 4)`)
* Standard Deviations: (`r round(range(apply(as_tibble(isee$sim[[1]]), 2, sd)), 4)`)

##### Overlapping

* Means: (`r round(range(apply(as_tibble(isee$sim[[101]]), 2, mean)), 4)`)
* Standard Deviations: (`r round(range(apply(as_tibble(isee$sim[[101]]), 2, sd)), 4)`)

### Correlations

```{r}
# Distinct
ggcorr(as_tibble(isee$sim[[1]]), limits = FALSE,
       hjust = 0.85, size = 2, layout.exp = 1) +
  labs(x = "Correlations for Distinct Simulations") +
  theme_minimal(base_size = 10)

```

```{r}
# Overlapping
ggcorr(as_tibble(isee$sim[[101]]), limits = FALSE,
       hjust = 0.85, size = 2, layout.exp = 1) +
  labs(x = "Correlations for Overlapping Simulations") +
  theme_minimal(base_size = 10)
```

