---
title: "EDCs in M&N"
author: "Lizzy Gibson"
date: "2/13/2021"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
options(scipen = 999)
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)
library(GGally)
library(R.matlab)
library(MNdata) # my data
library(janitor)
library(NMF)

source(here::here("./Results/compare_functions.R"))
source(here::here("./Results/fig_set.R"))
```

## Mothers & Newborns Cohort

* 5 phenols
* 3 parabens
* 9 phthalates

### Correlation

```{r}
edc <- 
  mn_edc %>% 
  dplyr::select(grep("sg_adj", colnames(.))) %>% 
  drop_na() %>% 
  clean_names()

names(edc) <- str_remove(names(edc), "_sg_adj")
edc_std <- apply(edc, 2, function(x) x/sd(x)) %>% as_tibble()

# rearrange to pht, phenol, parabens
edc_re <- edc %>% dplyr::select(1:11, 13, 16:17, 12, 14:15)

# corr does not care if you standardize
ggc <- ggcorr(edc_re, c("everything", "spearman"),
       size = 0,  # set this to zero
       layout.exp = 3) + 
       theme_minimal()

# Create labels and plot
lbs = str_pad(str_replace(str_to_upper(names(edc_re)), "_", "-"), 7)
cor_names <- tibble(x = seq(edc_re), y = seq(edc_re), 
                  lbs = lbs)

#pdf("./Apply/mn_edc_corr.pdf", width = 7, height = 5)
ggc + geom_text(data=cor_names, aes(x, y, label=lbs), 
                nudge_x = 2.25, nudge_y = 0.05, size = 4, color = "grey50")
#dev.off()
```

## BN2MF

```{r}
eh <- readMat(here::here("./Apply/mn2_EH.mat"))[[1]]
colnames(eh) <- toupper(names(edc))

applied <- eh[2:1,] %>% 
  as_tibble() %>% 
  dplyr::select(1:11, 13, 16:17, 12, 14:15) %>% 
  mutate(Pattern = 1:2) %>% 
  gather(key = Chemicals, value = Loadings, -Pattern) %>%
  mutate(Class = case_when(grepl("PB", Chemicals) ~ "Parabens",
                           grepl("^M[A-Z]", Chemicals) ~ "Phthalates",
                           TRUE ~ "Phenols"),
         Chemicals = str_replace(Chemicals, "_", "-")) %>% 
  mutate(Pattern = paste0("Pattern ", Pattern))
```

```{r, fig.width=18}
#pdf("Apply/mn2_edc_loadings.pdf", width = 18)
applied %>% 
  mutate(Chemicals = fct_inorder(Chemicals)) %>%
  ggplot(aes(x = Chemicals, y = Loadings, color = Class)) + 
  geom_point(size = 4) +
  geom_segment(aes(xend = Chemicals, yend = 0), size = 1.5) +
  facet_wrap(.~Pattern, scales = "free") +
  theme_bw(base_size = 25) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 18),
        strip.background = element_blank(),
        strip.text = element_text(size = 30),
        legend.title = element_blank(),
        legend.position = c(0.065, 0.85), # c(1,0) right bottom, c(1,1) right top.
        legend.background = element_rect(fill = "#ffffffaa", colour = NA)) +
  expand_limits(y=0) +
  scale_fill_nejm()
#dev.off()
```

```{r}
#pdf("Apply/mn2_edc_loadings_flip.pdf", width = 15)
applied %>% 
  mutate(Chemicals = fct_inorder(Chemicals)) %>%
  ggplot(aes(x = Loadings, y = Chemicals, color = Class)) + 
  geom_point(size = 4) +
  geom_segment(aes(yend = Chemicals, xend = 0), size = 1.5) +
  facet_wrap(.~Pattern, scales = "free_x") +
  theme_bw(base_size = 25) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 18),
        strip.background = element_blank(),
        strip.text = element_text(size = 30),
        legend.title = element_blank(),
        legend.position = c(0.4, 0.15), # c(1,0) right bottom, c(1,1) right top.
        legend.background = element_rect(fill = "#ffffffaa", colour = NA)) +
  expand_limits(y=0) +
  scale_fill_nejm()
#dev.off()

pdf("Apply/mn2_edc_loadings_tall.pdf", height = 10)
applied %>% 
  mutate(Chemicals = fct_inorder(Chemicals)) %>%
  ggplot(aes(x = Loadings, y = Chemicals, color = Class)) + 
  geom_point(size = 4) +
  geom_segment(aes(yend = Chemicals, xend = 0), size = 1.5) +
  facet_grid(Pattern~., scales = "free") +
  theme_bw(base_size = 25) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 18),
        strip.background = element_blank(),
        strip.text = element_text(size = 30),
        legend.title = element_blank(),
        legend.position = c(0.725, 0.6), # c(1,0) right bottom, c(1,1) right top.
        legend.background = element_rect(fill = "#ffffffaa", colour = NA)) +
  expand_limits(y=0) +
  scale_fill_nejm()
dev.off()
```

## Compare

### PCA

```{r}
prcomp(edc_std)$sdev
sum( prcomp(edc_std)$sdev[1:11]/sum(prcomp(edc_std)$sdev) )
# 11 > 80% var
# no obvious elbow
# 6 singular values > 1

plot(prcomp(edc_std))

as_tibble(prcomp(edc_std)$rotation) %>% 
  mutate(edc = colnames(edc)) %>% 
  pivot_longer(1:17) %>% 
  mutate(name = as.factor(name)) %>% 
  filter(name %in% c("PC1", "PC2", "PC3", "PC4", "PC5", "PC6")) %>% 
  ggplot(aes(x = edc, y = value)) + 
  geom_col() +
  facet_wrap(.~ name)
```

### NMF

```{r, nmf, cache=TRUE}
nmf_1 <- nmf(edc_std, rank = 1, nrun = 100, method = "lee")
nmf_2 <- nmf(edc_std, rank = 2, nrun = 100, method = "lee")
nmf_3 <- nmf(edc_std, rank = 3, nrun = 100, method = "lee")
nmf_4 <- nmf(edc_std, rank = 4, nrun = 100, method = "lee")
nmf_5 <- nmf(edc_std, rank = 5, nrun = 100, method = "lee")
nmf_6 <- nmf(edc_std, rank = 6, nrun = 100, method = "lee")

nmf_1p <- nmf(edc_std, rank = 1, nrun = 100)
nmf_2p <- nmf(edc_std, rank = 2, nrun = 100)
nmf_3p <- nmf(edc_std, rank = 3, nrun = 100)
nmf_4p <- nmf(edc_std, rank = 4, nrun = 100)
nmf_5p <- nmf(edc_std, rank = 5, nrun = 100)
nmf_6p <- nmf(edc_std, rank = 6, nrun = 100)
# default value is ‘brunet’ == KL

n = nrow(edc_std)
p = ncol(edc_std)

bic_1 <- sum((edc_std - (basis(nmf_1)%*%coef(nmf_1)))^2) + (1/2)*(n + p) * 1 * log(n * p)
bic_2 <- sum((edc_std - (basis(nmf_2)%*%coef(nmf_2)))^2) + (1/2)*(n + p) * 2 * log(n * p)
bic_3 <- sum((edc_std - (basis(nmf_3)%*%coef(nmf_3)))^2) + (1/2)*(n + p) * 3 * log(n * p)
bic_4 <- sum((edc_std - (basis(nmf_4)%*%coef(nmf_4)))^2) + (1/2)*(n + p) * 4 * log(n * p)
bic_5 <- sum((edc_std - (basis(nmf_5)%*%coef(nmf_5)))^2) + (1/2)*(n + p) * 5 * log(n * p)
bic_6 <- sum((edc_std - (basis(nmf_6)%*%coef(nmf_6)))^2) + (1/2)*(n + p) * 5 * log(n * p)

bic_1p <- sum((edc_std - (basis(nmf_1p)%*%coef(nmf_1p)))^2) + (1/2)*(n + p) * 1 * log(n * p)
bic_2p <- sum((edc_std - (basis(nmf_2p)%*%coef(nmf_2p)))^2) + (1/2)*(n + p) * 2 * log(n * p)
bic_3p <- sum((edc_std - (basis(nmf_3p)%*%coef(nmf_3p)))^2) + (1/2)*(n + p) * 3 * log(n * p)
bic_4p <- sum((edc_std - (basis(nmf_4p)%*%coef(nmf_4p)))^2) + (1/2)*(n + p) * 4 * log(n * p)
bic_5p <- sum((edc_std - (basis(nmf_5p)%*%coef(nmf_5p)))^2) + (1/2)*(n + p) * 5 * log(n * p)
bic_6p <- sum((edc_std - (basis(nmf_6p)%*%coef(nmf_6p)))^2) + (1/2)*(n + p) * 5 * log(n * p)
```

```{r}
coef(nmf_1) %>% 
  as_tibble() %>% 
  mutate(Pattern = 1:nrow(.)) %>% 
  gather(key = Chemicals, value = Loadings, -Pattern) %>%
  mutate(Group = ifelse(str_detect(Chemicals, "pb"), "Parabens",
                        ifelse(str_detect(Chemicals, "^m"), "Phthalates", "Phenols"))) %>% 
  arrange(Group) %>% 
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Pattern) + theme_bw() +
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))

coef(nmf_1p) %>% 
  as_tibble() %>% 
  mutate(Pattern = 1:nrow(.)) %>% 
  gather(key = Chemicals, value = Loadings, -Pattern) %>%
  mutate(Group = ifelse(str_detect(Chemicals, "pb"), "Parabens",
                        ifelse(str_detect(Chemicals, "^m"), "Phthalates", "Phenols"))) %>% 
  arrange(Group) %>% 
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Pattern) + theme_bw() +
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))
```


