---
title: "GNMF & Sim Data -- Iterate"
author: "Lizzy Gibson"
date: "2/25/2020"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
options(scipen = 999)
library(MNdata) # my data
library(reshape2) # melt
library(gridExtra) # gridarrange
library(bindata) # multivariate binomial dist
library(NMF) # rmatrix
library(MASS) # mvrnorm
library(tidyverse)
library(R.matlab)
```

# Load Sims

```{r}
load(here::here("./Sims/Iterate/sim_dist.RDA"))
sim_dist

load(here::here("./Sims/Iterate/sim_cor.RDA"))
sim_cor

load(here::here("./Sims/Iterate/sim_over.RDA"))
sim_over

labels <-  c("pcb28", "pcb66", "pcb74", "pcb99", "pcb105", "pcb118", "pcb138_158", "pcb146", "pcb153", "pcb156", "pcb167",
          "pcb170", "pcb178", "pcb183", "pcb187", "pcb180", "pcb189", "pcb194", "pcb196_203", "pcb199", "pcb206", "pcb209",
          "BDE17", "BDE28", "BDE47", "BDE66", "BDE85", "BDE99", "BDE100", "BDE153", "BDE154", "BDE183", "BDE209", "MECPP",
          "MEHHP", "MEOHP", "MCPP", "MIBP", "MBP", "MBZP", "MEP", "MEHP", "dcp_24", "dcp_25", "b_pb", "bp_3", "m_pb",
          "p_pb", "tcs", "bpa")
```

# GNMF Results

## 1. Distinct Patterns

```{r}
get_eh_dist <- function(seed) {
  eh <- readMat(here::here(paste0("./Sims/Iterate_Out/eh_dist_", seed, ".mat")))[[1]]
  eh <- as_tibble(eh)
}

eh_dist <- tibble(seed = 1:100) %>% 
  mutate(eh = map(seed, ~get_eh_dist(.x)))

for (i in 1:100) {
  colnames(eh_dist$eh[[i]]) <- labels
  
  eh_dist$eh[[i]] <- eh_dist$eh[[i]]
  }
```

```{r}
eh_dist_unnest <- eh_dist %>% 
  unnest(cols = c(eh))

# Reorder patterns
eh_dist_unnest %>% 
  mutate(pattern1 = ifelse(pcb146 > 0.5 & pcb28 > bpa, 1,
                          ifelse(BDE17 > 0.5, 2,
                                ifelse(MECPP > 0.5, 3,
                                       ifelse(tcs > 0.5, 4, 5))))) %>% pull(pattern1) %>% table()
```

### Scores

```{r}
get_ewa_dist <- function(seed) {
  ewa <- readMat(here::here(paste0("./Sims/Iterate_Out/ewa_dist_", seed, ".mat")))[[1]]
  ewa <- as_tibble(ewa)
}

ewa_dist <- tibble(seed = 1:100) %>% 
  mutate(ewa = map(seed, ~get_ewa_dist(.x)))

ewa_dist_unnest <- ewa_dist %>% 
  unnest(cols = c(ewa))
```

#### Match Scores

```{r}
full_dist <- full_join(eh_dist, ewa_dist, by = "seed") %>% 
    full_join(., sim_dist, by = "seed") %>% 
  select(-chem)

match_patterns <- function (eh_unnested) {
  eh_reordered <- eh_unnested %>% 
  mutate(pattern1 = ifelse(pcb146 > 0.5 & pcb28 > bpa, 1,
                          ifelse(BDE17 > 0.5, 2,
                                ifelse(MECPP > 0.5, 3,
                                       ifelse(tcs > 0.5, 4, 5))))) %>% # Switch patterns later to compare EH to loadings
  select(pattern1, everything())
  eh_reordered
}

match_scores <- function (patterns, scores) {
  N <- nrow(scores)
  for (j in 1:nrow(patterns)) {
    for (i in 1:ncol(scores)) {
      if (patterns[j, 2] == j && scores[1, i] == j) {
        scores[(N+1),i] = patterns[j,1]
      }
    }
  } 
  scores <- scores[c(1, nrow(scores), 2:(nrow(scores) - 1)),]
  scores
}

scores_matched_dist <- full_dist %>% 
    mutate(eh = map(eh, ~cbind(pattern = 1:nrow(.x), .x)),
         ewa = map(ewa, ~rbind(pattern = 1:ncol(.x), .x)),
         eh_reordered = map(eh, ~match_patterns(eh_unnested = .x)),
         ewa_reordered = ewa,
         ewa_reordered = map2(eh_reordered, ewa_reordered, ~match_scores(patterns = .x, scores = .y)))
```

#### Arrange Scores

```{r}
reorder_patterns <- function (eh_unnested) {
  eh_reordered <- eh_unnested %>% 
  arrange(pattern1) %>%
  mutate(pattern1 = fct_inorder(as.factor(pattern1)),
         pattern1 = as.integer(pattern1)) %>% 
    select(-pattern1, -pattern)
  eh_reordered
}

reorder_scores <- function (ewa_unnested) {
  ewa_reordered <- ewa_unnested %>% 
    t(.) %>% as_tibble(.) %>% 
  arrange(V2) %>%
  mutate(V2 = fct_inorder(as.factor(V2)),
         V2 = as.integer(V2)) %>% 
    t(.) %>% as_tibble(.) %>% 
    slice(3:nrow(.))
  ewa_reordered
}

scores_ordered_dist <- scores_matched_dist %>% 
  mutate(eh_reordered = map(eh_reordered, ~reorder_patterns(.x)),
         ewa_reordered = map(ewa_reordered, ~reorder_scores(.x)))
```

### Norms

```{r}
# All
full_dist %>%
  mutate(ewa = map(ewa, as.matrix),
         eh = map(eh, as.matrix)) %>% 
  mutate(pred = map2(ewa, eh, `%*%`)) %>% 
  mutate(norm_all = map2(sim, pred, ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary()
  
# Loadings (ordered, not standardized)
add_4 <- function(pattern) {
  
  if (nrow(pattern) == 3) {
  pattern <- rbind(pattern, four = rep(0, times = ncol(pattern))) %>% as_tibble(.)
  } else if (nrow(pattern) == 2) {
  pattern <- rbind(pattern, three = rep(0, times = ncol(pattern)), four = rep(0, times = ncol(pattern))) %>% as_tibble(.)
  } else {}
  pattern
}

add_3 <- function(score) {
  
  if (ncol(score) == 3) {
  score <- cbind(score, four = rep(0, times = nrow(score))) %>% as_tibble(.)
  } else if (ncol(score) == 2) {
  score <- cbind(score, three = rep(0, times = nrow(score)), four = rep(0, times = nrow(score))) %>% as_tibble(.)
  } else {}
  score
}

add_pattern <- function(pattern, true) {
  
  if (nrow(pattern) == 5) {
  true <- rbind(true, four = rep(0, times = ncol(true))) %>% as_tibble(.)
  } else if (nrow(pattern) == 6) {
  true <- rbind(true, three = rep(0, times = ncol(true)), four = rep(0, times = ncol(true))) %>% as_tibble(.)
  } else {}
  true
}

add_score <- function(score, true) {
  
  if (ncol(score) == 5) {
  true <- cbind(true, four = rep(0, times = nrow(true))) %>% as_tibble(.)
  } else if (ncol(score) == 6) {
  true <- cbind(true, three = rep(0, times = nrow(true)), four = rep(0, times = nrow(true))) %>% as_tibble(.)
  } else {}
  true
}

scores_ordered_dist %>% 
  mutate(patterns = map2(eh_reordered, patterns, add_pattern),
         scores = map2(ewa_reordered, scores, add_score)) %>% 
  mutate(norm_ehs = map2(patterns, eh_reordered, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_ehs) %>% 
  pull(norm_ehs) %>% summary()
```

```{r}
# Scores (ordered, not standardized)
scores_ordered_dist %>% 
  mutate(patterns = map2(eh_reordered, patterns, add_pattern),
         scores = map2(ewa_reordered, scores, add_score)) %>% 
  mutate(norm_scores = map2(scores, ewa_reordered, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_scores) %>% 
  pull(norm_scores) %>% summary()
```

### Viz

```{r}
eh_dist_reorder <- eh_dist_unnest %>%
  mutate(pattern1 = ifelse(pcb146 > 0.5 & pcb28 > bpa, 1,
                          ifelse(BDE17 > 0.5, 2,
                                ifelse(MECPP > 0.5, 3,
                                       ifelse(tcs > 0.5, 4, 5))))) %>%
  select(seed, pattern1, everything()) %>%
  arrange(seed, pattern1) %>%
  mutate(pattern1 = fct_inorder(as.factor(pattern1)),
         pattern1 = as.integer(pattern1))

eh_dist_reorder %>%
  gather(key = Chemicals, value = Loadings, -pattern1, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~pattern1) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

eh_dist_reorder %>% 
  gather(key = Chemicals, value = Loadings, -pattern1, -seed) %>% 
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = .45, outlier.shape = NA) +
  facet_wrap(.~pattern1) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

## 2. Correlated Scores

```{r}
get_eh_cor <- function(seed) {
  eh <- readMat(here::here(paste0("./Sims/Iterate_Out/eh_cor_", seed, ".mat")))[[1]]
  eh <- as_tibble(eh)
}

eh_cor <- tibble(seed = 1:100) %>% 
  mutate(eh = map(seed, ~get_eh_cor(.x)))

for (i in 1:100) {
  colnames(eh_cor$eh[[i]]) <- labels
  
  eh_cor$eh[[i]] <- eh_cor$eh[[i]]
  }

eh_cor_unnest <- eh_cor %>% 
  unnest(cols = c(eh)) 
```

```{r}
# Reorder patterns
eh_cor_unnest %>% 
  mutate(pattern1 = ifelse(pcb146 > 0.5 & pcb28 > bpa, 1,
                          ifelse(BDE17 > 0.5, 2,
                                ifelse(MECPP > 0.5, 3,
                                       ifelse(tcs > 0.5, 4, 5))))) %>% pull(pattern1) %>% table()
```

#### Scores

```{r}
get_ewa_cor <- function(seed) {
  ewa <- readMat(here::here(paste0("./Sims/Iterate_Out/ewa_cor_", seed, ".mat")))[[1]]
  ewa <- as_tibble(ewa)
}

ewa_cor <- tibble(seed = 1:100) %>% 
  mutate(ewa = map(seed, ~get_ewa_cor(.x)))

ewa_cor_unnest <- ewa_cor %>% 
  unnest(cols = c(ewa))
```

#### Match Scores

```{r}
full_cor <- full_join(eh_cor, ewa_cor, by = "seed") %>% 
    full_join(., sim_cor, by = "seed") %>% 
  select(-chem)

scores_matched_cor <- full_cor %>% 
  mutate(eh = map(eh, ~cbind(pattern = 1:nrow(.x), .x)),
         ewa = map(ewa, ~rbind(pattern = 1:ncol(.x), .x)),
         eh_reordered = map(eh, ~match_patterns(eh_unnested = .x)),
         ewa_reordered = ewa,
         ewa_reordered = map2(eh_reordered, ewa_reordered, ~match_scores(patterns = .x, scores = .y)))
```

#### Arrange Scores

```{r}
scores_ordered_cor <- scores_matched_cor %>% 
  mutate(eh_reordered = map(eh_reordered, ~reorder_patterns(.x)),
         ewa_reordered = map(ewa_reordered, ~reorder_scores(.x)))
```

### Norms

```{r}
# All
full_cor %>%
  mutate(ewa = map(ewa, as.matrix),
         eh = map(eh, as.matrix)) %>% 
  mutate(pred = map2(ewa, eh, `%*%`)) %>% 
  mutate(norm_all = map2(sim, pred, ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary()

scores_ordered_cor %>% 
  mutate(norm_ehs = map2(patterns, eh_reordered, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_ehs) %>% 
  pull(norm_ehs) %>% summary()
```

```{r}
# Scores (ordered, not standardized)
scores_ordered_cor %>% 
  mutate(norm_scores = map2(scores, ewa_reordered, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_scores) %>% 
  pull(norm_scores) %>% summary()
```

### Viz

```{r}
eh_cor_reorder <- eh_cor_unnest %>%
  mutate(pattern1 = ifelse(pcb146 > 0.5 & pcb28 > bpa, 1,
                          ifelse(BDE17 > 0.5, 2,
                                ifelse(MECPP > 0.5, 3,
                                       ifelse(tcs > 0.5, 4, 5))))) %>%
  select(seed, pattern1, everything()) %>%
  arrange(seed, pattern1) %>%
  mutate(pattern1 = fct_inorder(as.factor(pattern1)),
         pattern1 = as.integer(pattern1))

eh_cor_unnest %>%  
  mutate(pattern1 = ifelse(pcb146 > 0.5 & pcb28 > bpa, 1,
                          ifelse(BDE17 > 0.5, 2,
                                ifelse(MECPP > 0.5, 3,
                                       ifelse(tcs > 0.5, 4, 5))))) %>% 
  filter(seed == 3) %>% 
  gather(key = Chemicals, value = Loadings, -pattern1, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~pattern1) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

eh_cor_unnest %>%  
  mutate(pattern1 = ifelse(pcb146 > 0.5, 1,
                          ifelse(BDE17 > 0.5, 2,
                                ifelse(MECPP > 0.5, 3,
                                       ifelse(tcs > 0.5, 4, 5))))) %>% 
  gather(key = Chemicals, value = Loadings, -pattern1, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = .4, outlier.shape = NA) +
  facet_wrap(.~pattern1) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

## 3. Overlapping Patterns

```{r}
get_eh_over <- function(seed) {
  eh <- readMat(here::here(paste0("./Sims/Iterate_Out/eh_over_", seed, ".mat")))[[1]]
  eh <- as_tibble(eh)
}

eh_over <- tibble(seed = 1:100) %>% 
  mutate(eh = map(seed, ~get_eh_over(.x)))

for (i in 1:100) {
  colnames(eh_over$eh[[i]]) <- labels
  
  eh_over$eh[[i]] <- eh_over$eh[[i]]
  }

eh_over_unnest <- eh_over %>% 
  unnest(cols = c(eh))

eh_over_unnest %>% 
  mutate(pattern1 = ifelse(pcb146 > 0.5 & pcb28 > bpa, 1,
                          ifelse(BDE17 > 0.5, 2,
                                ifelse(MECPP > 0.5, 3,
                                       ifelse(tcs > 0.5, 4, 5))))) %>% pull(pattern1) %>% table()
```

### Scores

```{r}
get_ewa_over <- function(seed) {
  ewa <- readMat(here::here(paste0("./Sims/Iterate_Out/ewa_over_", seed, ".mat")))[[1]]
  ewa <- as_tibble(ewa)
}

ewa_over <- tibble(seed = 1:100) %>% 
  mutate(ewa = map(seed, ~get_ewa_over(.x)))

ewa_over_unnest <- ewa_over %>% 
  unnest(cols = c(ewa))

ewa_over_unnest %>% drop_na() %>% distinct(seed)
```

#### Match Scores

```{r}
full_over <- full_join(eh_over, ewa_over, by = "seed") %>% 
    full_join(., sim_over, by = "seed") %>% 
  select(-chem)

scores_matched_over <- full_over %>% 
  mutate(eh = map(eh, ~cbind(pattern = 1:nrow(.x), .x)),
         ewa = map(ewa, ~rbind(pattern = 1:ncol(.x), .x)),
         eh_reordered = map(eh, ~match_patterns(eh_unnested = .x)),
         ewa_reordered = ewa,
         ewa_reordered = map2(eh_reordered, ewa_reordered, ~match_scores(patterns = .x, scores = .y)))
```

#### Arrange Scores

```{r}
scores_ordered_over <- scores_matched_over %>% 
  mutate(eh_reordered = map(eh_reordered, ~reorder_patterns(.x)),
         ewa_reordered = map(ewa_reordered, ~reorder_scores(.x)))
```

### Norms

```{r}
# All
full_over %>%
  mutate(ewa = map(ewa, as.matrix),
         eh = map(eh, as.matrix)) %>% 
  mutate(pred = map2(ewa, eh, `%*%`)) %>% 
  mutate(norm_all = map2(sim, pred, ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary()

scores_ordered_over %>% 
  mutate(patterns = map2(eh_reordered, patterns, add_pattern),
         scores = map2(ewa_reordered, scores, add_score)) %>% 
  mutate(norm_ehs = map2(patterns, eh_reordered, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_ehs) %>% 
  pull(norm_ehs) %>% summary()
```

```{r}
# Scores (ordered, not standardized)
scores_ordered_over %>% 
  mutate(patterns = map2(eh_reordered, patterns, add_pattern),
         scores = map2(ewa_reordered, scores, add_score)) %>% 
  mutate(norm_scores = map2(scores, ewa_reordered, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_scores) %>% 
  pull(norm_scores) %>% summary()
```

### Viz

```{r}
eh_over_reorder <- eh_over_unnest %>%
  mutate(pattern1 = ifelse(pcb146 > 0.5 & pcb28 > bpa, 1,
                          ifelse(BDE17 > 0.5, 2,
                                ifelse(MECPP > 0.5, 3,
                                       ifelse(tcs > 0.5, 4, 5))))) %>%
  select(seed, pattern1, everything()) %>%
  arrange(seed, pattern1) %>%
  mutate(pattern1 = fct_inorder(as.factor(pattern1)),
         pattern1 = as.integer(pattern1))

eh_over_reorder %>% 
  gather(key = Chemicals, value = Loadings, -pattern1, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~pattern1) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

eh_over_reorder %>% 
  gather(key = Chemicals, value = Loadings, -pattern1, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = .45, outlier.shape = NA) +
  facet_wrap(.~pattern1) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

## Standardize

### Loadings

```{r}
standard <- function(row_matrix, column_matrix) {
  sum_row <- apply(row_matrix, 1, function(x) sum(x))
  row_out <-  as_tibble(apply(row_matrix, 1, function(x) x/sum(x))) # Divide patterns by pattern sum to normalize
  col_out <- map2_dfr(as_tibble(column_matrix), sum_row, function(x,y) x*y) # multiply scores by pattern sum
  list(row_out = row_out, col_out = col_out)
}

# head(col_out)
# head(col1_out)
# all.equal(col_out, col1_out)
# column_matrix <- scores_ordered_dist$scores[[1]]
# row_matrix <- scores_ordered_dist$patterns[[1]]
# colSums(standard(scores_ordered_dist$patterns[[19]], scores_ordered_dist$scores[[19]])[[1]])
# map2(scores_ordered_dist$patterns, scores_ordered_dist$scores, standard)

sd_dist_out <- scores_ordered_dist %>% 
  select(-eh, -ewa, -sim, -noise) %>% 
  mutate(sd_patterns = map2(patterns, scores, function(x,y) standard(x,y)[[1]]),
         sd_scores   = map2(patterns, scores, function(x,y) standard(x,y)[[2]]),
         sd_eh       = map2(eh_reordered, ewa_reordered,function(x,y) standard(x,y)[[1]]),
         sd_ewa      = map2(eh_reordered, ewa_reordered, function(x,y) standard(x,y)[[2]])) %>% 
  mutate(sd_patterns = map2(sd_eh, sd_patterns, add_score),
         sd_scores   = map2(sd_ewa, sd_scores, add_score)) %>%
  select(-eh_reordered, -ewa_reordered, -scores, -patterns)

sd_over_out <- scores_ordered_over %>% 
  select(-eh, -ewa, -sim, -noise) %>% 
  mutate(sd_patterns = map2(patterns, scores, function(x,y) standard(x,y)[[1]]),
         sd_scores   = map2(patterns, scores, function(x,y) standard(x,y)[[2]]),
         sd_eh       = map2(eh_reordered, ewa_reordered,function(x,y) standard(x,y)[[1]]),
         sd_ewa      = map2(eh_reordered, ewa_reordered, function(x,y) standard(x,y)[[2]])) %>% 
  mutate(sd_patterns = map2(sd_eh, sd_patterns, add_score),
         sd_scores   = map2(sd_ewa, sd_scores, add_score)) %>%
  select(-eh_reordered, -ewa_reordered, -scores, -patterns)

sd_cor_out <- scores_ordered_cor %>% 
  select(-eh, -ewa, -sim, -noise) %>% 
  mutate(sd_patterns = map2(patterns, scores, function(x,y) standard(x,y)[[1]]),
         sd_scores   = map2(patterns, scores, function(x,y) standard(x,y)[[2]]),
         sd_eh       = map2(eh_reordered, ewa_reordered,function(x,y) standard(x,y)[[1]]),
         sd_ewa      = map2(eh_reordered, ewa_reordered, function(x,y) standard(x,y)[[2]])) %>% 
  mutate(sd_patterns = map2(sd_eh, sd_patterns, add_score),
         sd_scores   = map2(sd_ewa, sd_scores, add_score)) %>%
  select(-eh_reordered, -ewa_reordered, -scores, -patterns)

dist_norm <- sd_dist_out %>%
mutate(norm_eh = map2(sd_patterns, sd_eh, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_eh) %>% 
  pull(norm_eh)

over_norm <- sd_over_out %>%   
mutate(norm_eh = map2(sd_patterns, sd_eh, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_eh) %>% 
  pull(norm_eh)
  
cor_norm <- sd_cor_out %>%   
mutate(norm_eh = map2(sd_patterns, sd_eh, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_eh) %>% 
  pull(norm_eh)

summary(over_norm) 
summary(cor_norm) 
summary(dist_norm)

(sum(over_norm) + sum(cor_norm) + sum(dist_norm)) / 300
```

### Scores

```{r}
dist_norm_ewa <- sd_dist_out %>% 
mutate(norm_ewa = map2(sd_scores, sd_ewa, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_ewa) %>% 
  pull(norm_ewa)

over_norm_ewa <- sd_over_out %>%   
mutate(norm_ewa = map2(sd_scores, sd_ewa, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_ewa) %>% 
  pull(norm_ewa)

cor_norm_ewa <- sd_cor_out %>%   
mutate(norm_ewa = map2(sd_scores, sd_ewa, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_ewa) %>% 
  pull(norm_ewa)

summary(over_norm_ewa) 
summary(cor_norm_ewa) 
summary(dist_norm_ewa)

(sum(over_norm_ewa) + sum(cor_norm_ewa) + sum(dist_norm_ewa)) / 300
```
