---
title: "PCA & Sim Data -- Iterate"
author: "Lizzy Gibson"
date: "2/26/2020"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
options(scipen = 999)
library(MNdata) # my data
library(reshape2) # melt
library(gridExtra) # gridarrange
library(bindata) # multivariate binomial dist
library(NMF) # rmatrix
library(MASS) # mvrnorm
library(tidyverse)
library(R.matlab)
```

## Load Sims

```{r, cache = TRUE}
load(here::here("./Sims/Iterate/sim_dist.RDA"))
sim_dist

load(here::here("./Sims/Iterate/sim_cor.RDA"))
sim_cor

load(here::here("./Sims/Iterate/sim_over.RDA"))
sim_over
```

## PCA

### Distinct Patterns

```{r, cache=TRUE}
labels <-  c("pcb28", "pcb66", "pcb74", "pcb99", "pcb105", "pcb118", "pcb138_158", "pcb146", "pcb153", "pcb156", "pcb167",
          "pcb170", "pcb178", "pcb183", "pcb187", "pcb180", "pcb189", "pcb194", "pcb196_203", "pcb199", "pcb206", "pcb209",
          "BDE17", "BDE28", "BDE47", "BDE66", "BDE85", "BDE99", "BDE100", "BDE153", "BDE154", "BDE183", "BDE209", "MECPP",
          "MEHHP", "MEOHP", "MCPP", "MIBP", "MBP", "MBZP", "MEP", "MEHP", "dcp_24", "dcp_25", "b_pb", "bp_3", "m_pb",
          "p_pb", "tcs", "bpa")

get_pca <- function (sim) {
  pca_out <- prcomp(sim)
  rotation <- as_tibble(pca_out$rotation)
  x <- as_tibble(pca_out$x)
  sv <- pca_out$sdev
  pred <- svd(sim)$u %*% diag(svd(sim)$d) %*% t(svd(sim)$v)
  list(rotation = rotation, ex = x, sv = sv, pred = pred)
}

pca_out_dist <- sim_dist %>% 
  mutate(rotations = map(sim, function(x) get_pca(x)[[1]]),
         ex = map(sim, function(x) get_pca(x)[[2]]),
         sv = map(sim, function(x) get_pca(x)[[3]]),
         pred = map(sim, function(x) get_pca(x)[[4]]))

#Explains > 80% variance
get_rank <- function (sv) {
  pve <- sv^2/sum(sv^2)
  rank <- 0
  for (i in 1:length(sv)) {
  if (sum(pve[1:i]) >= 0.8) {
    rank <- i
    break
  }}
    rank}

cut_rank <- function(rotations, ex, rank) {
  rotations <- rotations[, 1:rank] # this is variables x patterns
  ex <- ex[, 1:rank]
  list(rotations = rotations, ex = ex)
}
  
pca_out_dist <- pca_out_dist %>% 
  mutate(rank = map(sv, get_rank),
         rotations = pmap(list(rotations, ex, rank), 
                          function(x,y,z) cut_rank(x,y,z)[[1]]),
         ex =        pmap(list(rotations, ex, rank), 
                          function(x,y,z) cut_rank(x,y,z)[[2]]))

pca_out_dist %>% 
  mutate(rank = map(rank, as.factor)) %>% 
  unnest(rank) %>% 
  pull(rank) %>% table()
  
pca_rotations_dist <- pca_out_dist %>% select(seed, rotations) %>% unnest(cols = c(rotations))
```

#### Match Scores

```{r, match2, cache = TRUE}
match_patterns <- function (eh_unnested) {
    pca_reorder <- eh_unnested %>% 
      mutate(Chemicals = labels,
             Chemicals = fct_inorder(Chemicals)) %>% 
      gather(key = PC, value = Loadings, -Chemicals) %>%
      group_by(PC) %>%
      mutate(Loadings = case_when(
        any(PC == "PC1" & Chemicals == "pcb28" & Loadings < 0) ~ -Loadings,
        any(PC == "PC2" & Chemicals == "BDE99" & Loadings < 0) ~ -Loadings,
        any(PC == "PC3" & Chemicals == "bpa" & Loadings < 0) ~ -Loadings,
        any(PC == "PC4" & Chemicals == "BDE99" & Loadings < 0) ~ -Loadings,
        TRUE ~ Loadings
      )) %>%
      spread(PC, Loadings) %>% select(-Chemicals)
    pca_reorder
}

match_scores <- function (rotations, rotations_re, ex) {
  ex_re <- as_tibble(matrix(nrow = nrow(ex), ncol = ncol(ex)))
   for (k in 1:ncol(rotations)) {
      for (chem in 1:nrow(rotations)) {
        for (i in 1:nrow(ex)) {
        if (rotations[chem, k] == rotations_re[chem, k]) {
          ex_re[i, k] = ex[i, k]
        } else {ex_re[i, k] = -(ex[i, k])}
        }}}
  ex_re
}

scores_matched_dist <- pca_out_dist %>% 
  mutate(rotations_re = map(rotations, match_patterns),
         ex_re = pmap(list(rotations, rotations_re, ex), function(x,y,z)
           {match_scores(as.matrix(x), as.matrix(y), as.matrix(z))} #match_scores
                       ))
```

#### Norms

```{r, cache=TRUE}
#All
scores_matched_dist %>%
  mutate(norm_all = map2(sim, pred, function(x, y) {norm(as.matrix(x) - as.matrix(y), "F")/norm(as.matrix(x), "F")})) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary()
```

```{r, cache=TRUE}
# Loadings (ordered, not standardized)
# Not same size!
add_column <- function(pattern) {
  
  if (ncol(pattern) == 3) {
  pattern <- cbind(pattern, four = rep(0, times = nrow(pattern))) %>% as_tibble(.)
  } else if (ncol(pattern) == 2) {
  pattern <- cbind(pattern, three = rep(0, times = nrow(pattern)), four = rep(0, times = nrow(pattern))) %>% as_tibble(.)
  } else {}
  pattern
}

scores_matched_dist %>% 
  mutate(rotations_re = map(rotations_re, add_column)) %>% 
  mutate(norm_loadings = map2(patterns, rotations_re, 
                              ~norm(as.matrix(.x) - as.matrix(t(.y)), "F") /
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_loadings) %>% 
  pull(norm_loadings) %>% summary()
```

```{r, cache=TRUE}
# Scores (ordered, not standardized)
# Not same size!
scores_matched_dist %>% 
  mutate(ex_re = map(ex_re, add_column)) %>% 
  mutate(norm_scores = map2(scores, ex_re, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_scores) %>% 
  pull(norm_scores) %>% summary()
```

#### Viz

```{r, cache=TRUE}
pca_rotations_dist %>%  
  filter(seed == 100) %>%  
  as_tibble(.) %>% 
  mutate(Chemicals = labels) %>% 
  gather(key = PC, value = Loadings, -Chemicals) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
    group_by(PC) %>%
  mutate(Loadings = case_when(
    any(PC == "PC1" & Chemicals == "pcb28" & Loadings < 0) ~ -Loadings,
    any(PC == "PC2" & Chemicals == "BDE99" & Loadings < 0) ~ -Loadings,
    any(PC == "PC3" & Chemicals == "bpa" & Loadings < 0) ~ -Loadings,
    #any(PC == "PC4" & Chemicals == "BDE99" & Loadings < 0) ~ -Loadings,
    TRUE ~ Loadings # These dont change plot at all, should be able to standardize all 100 sims
  )) %>% filter(PC %in% c("PC1", "PC2", "PC3")) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~PC) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

scores_matched_dist %>%
  select(seed, rotations_re) %>% 
  unnest(rotations_re) %>% 
  mutate(Chemicals = rep(labels, 100)) %>% 
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = 0.4, outlier.shape = NA) +
  facet_wrap(.~PC) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

### Overlapping Patterns

```{r, cache=TRUE}
pca_out_over <- sim_over %>% 
  mutate(rotations = map(sim, function(x) get_pca(x)[[1]]),
         ex = map(sim, function(x) get_pca(x)[[2]]),
         sv = map(sim, function(x) get_pca(x)[[3]]),
         pred = map(sim, function(x) get_pca(x)[[4]]))

pca_out_over <- pca_out_over %>% 
  mutate(rank = map(sv, get_rank),
         rotations = pmap(list(rotations, ex, rank), 
                          function(x,y,z) cut_rank(x,y,z)[[1]]),
         ex =        pmap(list(rotations, ex, rank), 
                          function(x,y,z) cut_rank(x,y,z)[[2]]))

pca_out_over %>% 
  mutate(rank = map(rank, as.factor)) %>% 
  unnest(rank) %>% 
  pull(rank) %>% table()

pca_rotations_over <- pca_out_over %>% select(seed, rotations) %>% unnest(cols = c(rotations))
```

#### Match Scores

```{r, match1, cache = TRUE}
scores_matched_over <- pca_out_over %>% 
  mutate(rotations_re = map(rotations, match_patterns),
         ex_re = pmap(list(rotations, rotations_re, ex), function(x,y,z)
           {match_scores(as.matrix(x), as.matrix(y), as.matrix(z))} #match_scores
                       ))
```

#### Norms

```{r, cache = TRUE}
#All
scores_matched_over %>%
  mutate(norm_all = map2(sim, pred, function(x, y) {norm(as.matrix(x) - as.matrix(y), "F")/norm(as.matrix(x), "F")})) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary()
```

```{r, cache = TRUE}
# Loadings (ordered, not standardized)
# Not same size!
scores_matched_over %>% 
  mutate(rotations_re = map(rotations_re, add_column)) %>% 
  mutate(norm_loadings = map2(patterns, rotations_re, 
                              ~norm(as.matrix(.x) - as.matrix(t(.y)), "F") /
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_loadings) %>% 
  pull(norm_loadings) %>% summary()
```

```{r, cache = TRUE}
# Scores (ordered, not standardized)
# Not same size!
scores_matched_over %>% 
  mutate(ex_re = map(ex_re, add_column)) %>% 
  mutate(norm_scores = map2(scores, ex_re, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_scores) %>% 
  pull(norm_scores) %>% summary()
```

#### Viz

```{r, cache = TRUE}
pca_rotations_over %>%  
  filter(seed == 100) %>%  
  as_tibble(.) %>% 
  mutate(Chemicals = labels) %>% 
  gather(key = PC, value = Loadings, -Chemicals) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
    group_by(PC) %>%
  mutate(Loadings = case_when(
    any(PC == "PC1" & Chemicals == "pcb28" & Loadings < 0) ~ -Loadings,
    any(PC == "PC2" & Chemicals == "BDE99" & Loadings < 0) ~ -Loadings,
    any(PC == "PC3" & Chemicals == "bpa" & Loadings < 0) ~ -Loadings,
    #any(PC == "PC4" & Chemicals == "BDE99" & Loadings < 0) ~ -Loadings,
    TRUE ~ Loadings # These dont change plot at all, should be able to standardize all 100 sims
  )) %>% filter(PC %in% c("PC1", "PC2", "PC3")) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~PC) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

scores_matched_over %>%
  select(seed, rotations_re) %>% 
  unnest(rotations_re) %>% 
  mutate(Chemicals = rep(labels, 100)) %>% 
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = 0.4, outlier.shape = NA) +
  facet_wrap(.~PC) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

### Correlated  Scores

```{r, cache = TRUE}
pca_out_cor <- sim_cor %>% 
  mutate(rotations = map(sim, function(x) get_pca(x)[[1]]),
         ex = map(sim, function(x) get_pca(x)[[2]]),
         sv = map(sim, function(x) get_pca(x)[[3]]),
         pred = map(sim, function(x) get_pca(x)[[4]]))

pca_out_cor <- pca_out_cor %>% 
  mutate(rank = map(sv, get_rank),
         rotations = pmap(list(rotations, ex, rank), 
                          function(x,y,z) cut_rank(x,y,z)[[1]]),
         ex =        pmap(list(rotations, ex, rank), 
                          function(x,y,z) cut_rank(x,y,z)[[2]]))

pca_out_cor %>% 
  mutate(rank = map(rank, as.factor)) %>% 
  unnest(rank) %>% 
  pull(rank) %>% table()

pca_rotations_cor <- pca_out_cor %>% select(seed, rotations) %>% unnest(cols = c(rotations))
```

#### Match Scores

```{r, match3, cache = TRUE}
scores_matched_cor <- pca_out_cor %>% 
  mutate(rotations_re = map(rotations, match_patterns),
         ex_re = pmap(list(rotations, rotations_re, ex), function(x,y,z)
           {match_scores(as.matrix(x), as.matrix(y), as.matrix(z))} #match_scores
                       ))
```

#### Norms

```{r, cache = TRUE}
#All
scores_matched_cor %>%
  mutate(norm_all = map2(sim, pred, function(x, y) {norm(as.matrix(x) - as.matrix(y), "F")/norm(as.matrix(x), "F")})) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary()
```

```{r, cache = TRUE}
# Loadings (ordered, not standardized)
# Not same size!
scores_matched_cor %>% 
  mutate(rotations_re = map(rotations_re, add_column)) %>% 
  mutate(norm_loadings = map2(patterns, rotations_re, 
                              ~norm(as.matrix(.x) - as.matrix(t(.y)), "F") /
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_loadings) %>% 
  pull(norm_loadings) %>% summary()
```

```{r, cache = TRUE}
# Scores (ordered, not standardized)
# Not same size!
scores_matched_cor %>% 
  mutate(ex_re = map(ex_re, add_column)) %>% 
  mutate(norm_scores = map2(scores, ex_re, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_scores) %>% 
  pull(norm_scores) %>% summary()
```

#### Viz

```{r, cach = TRUE}
pca_rotations_cor %>%  
  filter(seed == 100) %>%  
  as_tibble(.) %>% 
  mutate(Chemicals = labels) %>% 
  gather(key = PC, value = Loadings, -Chemicals) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
    group_by(PC) %>%
  mutate(Loadings = case_when(
    any(PC == "PC1" & Chemicals == "pcb28" & Loadings < 0) ~ -Loadings,
    any(PC == "PC2" & Chemicals == "BDE99" & Loadings < 0) ~ -Loadings,
    any(PC == "PC3" & Chemicals == "bpa" & Loadings < 0) ~ -Loadings,
    #any(PC == "PC4" & Chemicals == "BDE99" & Loadings < 0) ~ -Loadings,
    TRUE ~ Loadings # These dont change plot at all, should be able to standardize all 100 sims
  )) %>% filter(PC %in% c("PC1", "PC2", "PC3")) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~PC) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

scores_matched_cor %>%
  select(seed, rotations_re) %>% 
  unnest(rotations_re) %>% 
  mutate(Chemicals = rep(labels, 100)) %>% 
  gather(key = PC, value = Loadings, -Chemicals, -seed) %>%
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = 0.4, outlier.shape = NA) +
  facet_wrap(.~PC) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

## Standardize

Divide coefs by stdev. Multiply scores by stdev of associated coef.

```{r, cache = TRUE}
add_row_truth <- function(pattern, true) {
  
  if (nrow(pattern) == 5) {
  true <- rbind(true, four = rep(0, times = ncol(true))) %>% as_tibble(.)
  } else if (nrow(pattern) == 6) {
  true <- rbind(true, three = rep(0, times = ncol(true)), four = rep(0, times = ncol(true))) %>% as_tibble(.)
  } else {}
  true
}

add_column_truth <- function(score, true) {
  
  if (ncol(score) == 5) {
  true <- cbind(true, four = rep(0, times = nrow(true))) %>% as_tibble(.)
  } else if (ncol(score) == 6) {
  true <- cbind(true, three = rep(0, times = nrow(true)), four = rep(0, times = nrow(true))) %>% as_tibble(.)
  } else {}
  true
}

standard <- function(loading_matrix, score_matrix) {
  sum_row <- apply(loading_matrix, 1, function(x) sum(x))
  pattern_out <-  as_tibble(apply(loading_matrix, 1, function(x) x/sum(x))) # Divide patterns by pattern sum to normalize
  score_out <- map2_dfr(as_tibble(score_matrix), sum_row, function(x,y) x*y) # multiply scores by pattern sum
  list(pattern_out = pattern_out, score_out = score_out)
}

sd_dist_out <- scores_matched_dist %>% 
  mutate(sd_patterns = map2(patterns, scores, function(x,y) standard(x,y)[[1]]), # Normalize and Standardize first
         sd_scores   = map2(patterns, scores, function(x,y) standard(x,y)[[2]]),
         sd_basis    = map2(rotations_re, ex_re,function(x,y) standard(t(x),y)[[2]]),
         sd_coef     = map2(rotations_re, ex_re, function(x,y) standard(t(x),y)[[1]])) %>% 
  mutate(sd_patterns = map2(sd_coef, sd_patterns, add_row_truth),             # then add extra row/column for norm compatibility
         sd_scores   = map2(sd_basis, sd_scores, add_column_truth),
         sd_coef     = map(sd_coef, add_column),
         sd_basis    = map(sd_basis, add_column)) %>%
  select(-rotations_re, -ex_re, -scores, -patterns)
```

```{r, cache = TRUE}
dist_norm <- sd_dist_out %>% 
mutate(norm_coef = map2(sd_patterns, sd_coef, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_coef) %>% 
  pull(norm_coef)
```

```{r, cache = TRUE}
sd_over_out <- scores_matched_over %>% 
  mutate(sd_patterns = map2(patterns, scores, function(x,y) standard(x,y)[[1]]),
         sd_scores   = map2(patterns, scores, function(x,y) standard(x,y)[[2]]),
         sd_basis    = map2(rotations_re, ex_re,function(x,y) standard(t(x),y)[[2]]),
         sd_coef     = map2(rotations_re, ex_re, function(x,y) standard(t(x),y)[[1]])) %>% 
  mutate(sd_patterns = map2(sd_coef, sd_patterns, add_row_truth),
         sd_scores   = map2(sd_basis, sd_scores, add_column_truth),
         sd_coef     = map(sd_coef, add_column),
         sd_basis    = map(sd_basis, add_column)) %>%
  select(-rotations_re, -ex_re, -scores, -patterns)
```

```{r, cache = TRUE}
over_norm <- sd_over_out %>%   
mutate(norm_coef = map2(sd_patterns, sd_coef, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_coef) %>% 
  pull(norm_coef)

sd_cor_out <- scores_matched_cor %>%
  mutate(sd_patterns = map2(patterns, scores, function(x,y) standard(x,y)[[1]]),
         sd_scores   = map2(patterns, scores, function(x,y) standard(x,y)[[2]]),
         sd_basis    = map2(rotations_re, ex_re,function(x,y) standard(t(x),y)[[2]]),
         sd_coef     = map2(rotations_re, ex_re, function(x,y) standard(t(x),y)[[1]])) %>% 
  mutate(sd_patterns = map2(sd_coef, sd_patterns, add_row_truth),
         sd_scores   = map2(sd_basis, sd_scores, add_column_truth),
         sd_coef     = map(sd_coef, add_column),
         sd_basis    = map(sd_basis, add_column)) %>%
  select(-rotations_re, -ex_re, -scores, -patterns)
  
cor_norm <- sd_cor_out %>%   
mutate(norm_coef = map2(sd_patterns, sd_coef, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_coef) %>% 
  pull(norm_coef)

summary(over_norm) 
summary(cor_norm) 
summary(dist_norm)

(sum(over_norm) + sum(cor_norm) + sum(dist_norm)) / 300
```

```{r, cache = TRUE}
dist_norm_basis <- sd_dist_out %>% 
mutate(norm_basis = map2(sd_scores, sd_basis, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_basis) %>% 
  pull(norm_basis)

over_norm_basis <- sd_over_out %>%   
mutate(norm_basis = map2(sd_scores, sd_basis, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_basis) %>% 
  pull(norm_basis)

cor_norm_basis <- sd_cor_out %>%   
mutate(norm_basis = map2(sd_scores, sd_basis, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_basis) %>% 
  pull(norm_basis)

summary(over_norm_basis) 
summary(cor_norm_basis) 
summary(dist_norm_basis)

(sum(over_norm_basis) + sum(cor_norm_basis) + sum(dist_norm_basis)) / 300
```

## Summarize

### Rank

```{r}
rank_d <- pca_out_dist %>% 
  select(rank) %>% 
  unnest(rank) %>%
  group_by(rank) %>% 
  summarise(n = n()) %>% 
  mutate(Simulation = "Distinct") %>% 
  mutate(Proportion = n/100) %>% 
  select(Simulation, Rank = rank, Proportion)

rank_o <- pca_out_over %>% 
  select(rank) %>% 
  unnest(rank) %>%
  group_by(rank) %>% 
  summarise(n = n()) %>% 
  mutate(Simulation = "Overlapping") %>% 
  mutate(Proportion = n/100) %>% 
  select(Simulation, Rank = rank, Proportion)

rank_c <- pca_out_cor %>% 
  select(rank = rank) %>% 
  unnest(rank) %>%
  group_by(rank) %>% 
  summarise(n = n()) %>% 
  mutate(Simulation = "Correlated") %>% 
  mutate(Proportion = n/100) %>% 
  select(Simulation, Rank = rank, Proportion)


rbind(rank_d, rank_o, rank_c) %>% knitr::kable()

```

### Norms

#### Unstandardized

```{r}
dist_pred <- scores_matched_dist %>%
  mutate(norm_all = map2(sim, pred, function(x, y) {norm(as.matrix(x) - as.matrix(y), "F")/norm(as.matrix(x), "F")})) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Prediction Error",
                         Simulation = "Distinct",
                         Standardized = "No") %>% 
  select(Simulation, Norm, Standardized, everything())

dist_load <- scores_matched_dist %>% 
  mutate(rotations_re = map(rotations_re, add_column)) %>% 
  mutate(norm_loadings = map2(patterns, rotations_re, 
                              ~norm(as.matrix(.x) - as.matrix(t(.y)), "F") /
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_loadings) %>% 
  pull(norm_loadings) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Pattern Loading Error",
                         Simulation = "Distinct",
                         Standardized = "No") %>% 
  select(Simulation, Norm, Standardized, everything())

dist_score <- scores_matched_dist %>% 
  mutate(ex_re = map(ex_re, add_column)) %>% 
  mutate(norm_scores = map2(scores, ex_re, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_scores) %>% 
  pull(norm_scores) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Pattern Score Error",
                         Simulation = "Distinct",
                         Standardized = "No") %>% 
  select(Simulation, Norm, Standardized, everything())
```

```{r}
over_pred <- scores_matched_over %>%
  mutate(norm_all = map2(sim, pred, function(x, y) {norm(as.matrix(x) - as.matrix(y), "F")/norm(as.matrix(x), "F")})) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Prediction Error",
                         Simulation = "Distinct",
                         Standardized = "No") %>% 
  select(Simulation, Norm, Standardized, everything())

over_load <- scores_matched_over %>% 
  mutate(rotations_re = map(rotations_re, add_column)) %>% 
  mutate(norm_loadings = map2(patterns, rotations_re, 
                              ~norm(as.matrix(.x) - as.matrix(t(.y)), "F") /
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_loadings) %>% 
  pull(norm_loadings) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Pattern Loading Error",
                         Simulation = "Distinct",
                         Standardized = "No") %>% 
  select(Simulation, Norm, Standardized, everything())

over_score <- scores_matched_over %>% 
  mutate(ex_re = map(ex_re, add_column)) %>% 
  mutate(norm_scores = map2(scores, ex_re, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_scores) %>% 
  pull(norm_scores) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Score Error",
                         Simulation = "Distinct",
                         Standardized = "No") %>% 
  select(Simulation, Norm, Standardized, everything())
```

```{r}
cor_pred <- scores_matched_cor %>%
  mutate(norm_all = map2(sim, pred, function(x, y) {norm(as.matrix(x) - as.matrix(y), "F")/norm(as.matrix(x), "F")})) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Prediction Error",
                         Simulation = "Distinct",
                         Standardized = "No") %>% 
  select(Simulation, Norm, Standardized, everything())

cor_load <- scores_matched_cor %>% 
  mutate(rotations_re = map(rotations_re, add_column)) %>% 
  mutate(norm_loadings = map2(patterns, rotations_re, 
                              ~norm(as.matrix(.x) - as.matrix(t(.y)), "F") /
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_loadings) %>% 
  pull(norm_loadings) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Pattern Loading Error",
                         Simulation = "Distinct",
                         Standardized = "No") %>% 
  select(Simulation, Norm, Standardized, everything())

cor_score <- scores_matched_cor %>% 
  mutate(ex_re = map(ex_re, add_column)) %>% 
  mutate(norm_scores = map2(scores, ex_re, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_scores) %>% 
  pull(norm_scores) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Score Error",
                         Simulation = "Distinct",
                         Standardized = "No") %>% 
  select(Simulation, Norm, Standardized, everything())
```

```{r}
rbind(dist_pred,
      dist_load,
      dist_score, 
      over_pred,
      over_load,
      over_score,
      cor_pred,
      cor_load,
      cor_score) %>% knitr::kable()
```

#### Standardized

```{r}
over_load_s <- summary(over_norm) %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Pattern Loading Error",
                         Simulation = "Overlapping",
                         Standardized = "Yes") %>% 
  select(Simulation, Norm, Standardized, everything())

cor_load_s <- summary(cor_norm) %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Pattern Loading Error",
                         Simulation = "Correlated",
                         Standardized = "Yes") %>% 
  select(Simulation, Norm, Standardized, everything())

dist_load_s <- summary(dist_norm) %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Pattern Loading Error",
                         Simulation = "Distinct",
                         Standardized = "Yes") %>% 
  select(Simulation, Norm, Standardized, everything())
```

```{r}
over_score_s <- summary(over_norm_basis) %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Score Error",
                         Simulation = "Overlapping",
                         Standardized = "Yes") %>% 
  select(Simulation, Norm, Standardized, everything())

cor_score_s <- summary(cor_norm_basis) %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Score Error",
                         Simulation = "Correlated",
                         Standardized = "Yes") %>% 
  select(Simulation, Norm, Standardized, everything())

dist_score_s <- summary(dist_norm_basis) %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Relative Score Error",
                         Simulation = "Distinct",
                         Standardized = "Yes") %>% 
  select(Simulation, Norm, Standardized, everything())
```

```{r}
rbind(dist_load_s,
      dist_score_s, 
      over_load_s,
      over_score_s,
      cor_load_s,
      cor_score_s) %>% knitr::kable()
```

