---
title: "Poisson NMF -- Not Stand & Wrong L"
author: "Lizzy Gibson"
date: "2/27/2020"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    code_folding: hide
---

```{r setup, include=FALSE}
options(scipen = 999)
library(MNdata) # my data
library(reshape2) # melt
library(gridExtra) # gridarrange
library(bindata) # multivariate binomial dist
library(NMF) # rmatrix
library(MASS) # mvrnorm
library(tidyverse)
library(R.matlab)
```

## Load Sims

```{r, load, cache = TRUE}
load(here::here("./R/Sims/Iterate/sim_dist_old.RDA"))

load(here::here("./R/Sims/Iterate/sim_cor_old.RDA"))

load(here::here("./R/Sims/Iterate/sim_over_old.RDA"))
```

## Distinct Patterns

```{r, long1, cache = TRUE}
get_nmf_div <- function (sim) {
  set.seed(1988)
  nmf_3 <- nmf(sim, 3, nrun = 100, method = "brunet")
  nmf_4 <- nmf(sim, 4, nrun = 100, method = "brunet")
  nmf_5 <- nmf(sim, 5, nrun = 100, method = "brunet")
  
  bic_3 <- (residuals(nmf_3)) + (1/2)*(nrow(sim) + ncol(sim)) * 3 * log(nrow(sim) * ncol(sim))
  bic_4 <- (residuals(nmf_4)) + (1/2)*(nrow(sim) + ncol(sim)) * 4 * log(nrow(sim) * ncol(sim))
  bic_5 <- (residuals(nmf_5)) + (1/2)*(nrow(sim) + ncol(sim)) * 5 * log(nrow(sim) * ncol(sim))
  
 if (bic_3 <= bic_4) {
    nmf_out <- nmf_3
    rank <- 3
  } else if (bic_4 < bic_3 &&
             bic_4 <= bic_5) {
    nmf_out <- nmf_4
    rank <- 4
  } else {
    nmf_out <- nmf_5
    rank <- 5}
  
  basis <- as_tibble(basis(nmf_out))
  coef <- as_tibble(coef(nmf_out))
  pred <- basis(nmf_out) %*% coef(nmf_out)
  list(basis = basis, coef = coef, pred = pred, rank = rank)
  }

nmf_out_dist <- sim_dist %>%
  mutate(nmf_out = map(sim, get_nmf_div),
        coef = map(nmf_out, function(x) {x[[2]]}),
         pred = map(nmf_out, function(x) {x[[3]]}),
         basis = map(nmf_out, function(x) {x[[1]]}),
        rank = map(nmf_out, function(x) {x[[4]]}))
```

## Overlapping Patterns

```{r, over, cache = TRUE}
nmf_out_over <- sim_over %>%
    mutate(nmf_out = map(sim, get_nmf_div),
        coef = map(nmf_out, function(x) {x[[2]]}),
         pred = map(nmf_out, function(x) {x[[3]]}),
         basis = map(nmf_out, function(x) {x[[1]]}),
        rank = map(nmf_out, function(x) {x[[4]]}))
```

## Correlated Scores

```{r, corr, cache = TRUE}
nmf_out_cor <- sim_cor %>%
    mutate(nmf_out = map(sim, get_nmf_div),
        coef = map(nmf_out, function(x) {x[[2]]}),
         pred = map(nmf_out, function(x) {x[[3]]}),
         basis = map(nmf_out, function(x) {x[[1]]}),
        rank = map(nmf_out, function(x) {x[[4]]}))
```

### Rank

```{r}
rank_d <- nmf_out_dist %>% 
  mutate(rank = map(coef, nrow)) %>% 
  select(rank) %>%
  unnest(rank) %>%
  group_by(rank) %>%
  summarise(n = n()) %>%
  mutate(Simulation = "Distinct") %>%
  mutate(Proportion = n/100) %>%
  select(Simulation, Rank = rank, Proportion)

rank_o <- nmf_out_over %>%
  mutate(rank = map(coef, nrow)) %>%
  select(rank) %>%
  unnest(rank) %>%
  group_by(rank) %>%
  summarise(n = n()) %>%
  mutate(Simulation = "Overlapping") %>%
  mutate(Proportion = n/100) %>%
  select(Simulation, Rank = rank, Proportion)

rank_c <- nmf_out_cor %>%
  mutate(rank = map(coef, nrow)) %>%
  select(rank = rank) %>%
  unnest(rank) %>%
  group_by(rank) %>%
  summarise(n = n()) %>%
  mutate(Simulation = "Correlated") %>%
  mutate(Proportion = n/100) %>%
  select(Simulation, Rank = rank, Proportion)


rbind(rank_d, rank_o, rank_c) %>% knitr::kable()
```

```{r}
nmf_out_dist %>% dplyr::select(rank) %>% unnest() %>% table(.)
nmf_out_over %>% dplyr::select(rank) %>% unnest() %>% table(.)
nmf_out_cor %>% dplyr::select(rank) %>% unnest() %>% table(.)
```
