---
title: "Factor Analysis & Sim Data -- Iterate"
author: "Lizzy Gibson"
date: "3/5/2020"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    code_folding: hide
---

```{r setup, include=FALSE}
options(scipen = 999)
library(MNdata) # my data
library(reshape2) # melt
library(gridExtra) # gridarrange
library(bindata) # multivariate binomial dist
library(NMF) # rmatrix
library(MASS) # mvrnorm
library(tidyverse)
library(R.matlab)
library(psych)
```

## Load Sims

```{r}
load(here::here("./Sims/Iterate/sim_dist.RDA"))

load(here::here("./Sims/Iterate/sim_cor.RDA"))

load(here::here("./Sims/Iterate/sim_over.RDA"))
```

## Distinct Patterns

```{r, fa1}
get_fa <- function (sim) {
  set.seed(1988)
  fa_3 <- fa(sim, 3, scores = "regression", rotate = "promax")
  fa_4 <- fa(sim, 4, scores = "regression", rotate = "promax")
  fa_5 <- fa(sim, 5, scores = "regression", rotate = "promax")
  
 if (fa_5$BIC < fa_4$BIC && fa_5$BIC < fa_3$BIC) {
    fa_out <- fa_5
  } else if (fa_4$BIC < fa_3$BIC && fa_4$BIC < fa_5$BIC) {
    fa_out <- fa_4
  } else {fa_out <- fa_3}
    
  loadings <- matrix(fa_out$loadings, ncol = ncol(fa_out$scores))
  fa_scores <- fa_out$scores
  pred <- fa_scores %*% t(loadings)
  list(fa_scores = fa_scores, loadings = loadings, pred = pred)
}

fa_out_dist <- sim_dist %>% 
  mutate(fa_out = map(sim, get_fa),
        loadings = map(fa_out, function(x){x[[2]]}),
        pred = map(fa_out, function(x){x[[3]]}),
        fa_scores = map(fa_out, function(x){x[[1]]}))

fa_loadings_dist <- fa_out_dist %>% select(seed, loadings) %>% 
        mutate(loadings = map(loadings, as_tibble)) %>% 
        unnest(loadings)

labels <-  c("pcb28", "pcb66", "pcb74", "pcb99", "pcb105", "pcb118", "pcb138_158", "pcb146", "pcb153", "pcb156", "pcb167",
          "pcb170", "pcb178", "pcb183", "pcb187", "pcb180", "pcb189", "pcb194", "pcb196_203", "pcb199", "pcb206", "pcb209",
          "BDE17", "BDE28", "BDE47", "BDE66", "BDE85", "BDE99", "BDE100", "BDE153", "BDE154", "BDE183", "BDE209", "MECPP",
          "MEHHP", "MEOHP", "MCPP", "MIBP", "MBP", "MBZP", "MEP", "MEHP", "dcp_24", "dcp_25", "b_pb", "bp_3", "m_pb",
          "p_pb", "tcs", "bpa")
```

### Viz

```{r, fa2}
fa_loadings_dist %>%  
  filter(seed == 77) %>% 
  mutate(Chemicals = labels) %>% 
  select(seed, Chemicals, V1:V4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

fa_loadings_dist %>%  
  mutate(Chemicals = rep(labels, 100)) %>% 
  select(seed, Chemicals, V1:V4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = .45, outlier.shape = NA) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

## Overlapping Patterns

```{r, fa3, warning=FALSE}
fa_out_over <- sim_over %>% 
  mutate(fa_out = map(sim, get_fa),
        loadings = map(fa_out, function(x){x[[2]]}),
        pred = map(fa_out, function(x){x[[3]]}),
        fa_scores = map(fa_out, function(x){x[[1]]}))

fa_loadings_over <- fa_out_over %>% select(seed, loadings) %>% 
  mutate(loadings = map(loadings, as_tibble)) %>% 
  unnest(loadings)
```

### Viz

```{r, fa4}
fa_loadings_over %>%  
  filter(seed == 7) %>% 
  mutate(Chemicals = labels) %>% 
  select(seed, Chemicals, V1:V4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

fa_loadings_over %>%  
  mutate(Chemicals = rep(labels, 100)) %>% 
  select(seed, Chemicals, V1:V4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = .45, outlier.shape = NA) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

## Correlated Scores

```{r, fa5, warning=FALSE}
fa_out_cor <- sim_cor %>% 
  mutate(fa_out = map(sim, get_fa),
        loadings = map(fa_out, function(x){x[[2]]}),
        pred = map(fa_out, function(x){x[[3]]}),
        fa_scores = map(fa_out, function(x){x[[1]]}))

fa_loadings_cor <- fa_out_cor %>% select(seed, loadings) %>% 
  mutate(loadings = map(loadings, as_tibble)) %>% 
  unnest(loadings)
```

### Viz

```{r, fa6}
fa_loadings_cor %>%  
  filter(seed == 7) %>% 
  mutate(Chemicals = labels) %>% 
  select(seed, Chemicals, V1:V4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

fa_loadings_cor %>%  
  mutate(Chemicals = rep(labels, 100)) %>% 
  select(seed, Chemicals, V1:V4) %>% 
  gather(key = Factor, value = Loadings, -Chemicals, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = Loadings)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = .45, outlier.shape = NA) +
  facet_wrap(.~Factor) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

## Summarize

### Rank

```{r, fa7}
fa_rank_d <- fa_out_dist %>% 
  mutate(rank = map(loadings, ncol)) %>% 
  select(rank) %>%
  unnest(rank) %>%
  group_by(rank) %>%
  summarise(n = n()) %>%
  mutate(Simulation = "Distinct") %>%
  mutate(Proportion = n/100) %>%
  select(Simulation, Rank = rank, Proportion)

fa_rank_o <- fa_out_over %>% 
  mutate(rank = map(loadings, ncol)) %>%
  select(rank) %>%
  unnest(rank) %>%
  group_by(rank) %>%
  summarise(n = n()) %>%
  mutate(Simulation = "Overlapping") %>%
  mutate(Proportion = n/100) %>%
  select(Simulation, Rank = rank, Proportion)

fa_rank_c <- fa_out_cor %>% 
  mutate(rank = map(loadings, ncol)) %>%
  select(rank = rank) %>%
  unnest(rank) %>%
  group_by(rank) %>%
  summarise(n = n()) %>%
  mutate(Simulation = "Correlated") %>%
  mutate(Proportion = n/100) %>%
  select(Simulation, Rank = rank, Proportion)

rbind(fa_rank_d, fa_rank_o, fa_rank_c) %>% knitr::kable()
```

### Norms

#### Unstandardized

```{r, fa8}
fa_dist_pred <- fa_out_dist %>%
  mutate(norm_all = map2(sim, pred, function(x, y) {norm(as.matrix(x) - as.matrix(y), "F")/norm(as.matrix(x), "F")})) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Prediction",
                         Simulation = "Distinct",
                         Standardized = "No") %>% 
  select(Norm, Simulation, Standardized, everything())

fa_dist_load <- fa_out_dist %>% 
  mutate(norm_loadings = map2(patterns, loadings, 
                              ~norm(as.matrix(.x) - as.matrix(t(.y)), "F") /
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_loadings) %>% 
  pull(norm_loadings) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Loadings",
                         Simulation = "Distinct",
                         Standardized = "No") %>% 
  select(Norm, Simulation, Standardized, everything())

fa_dist_score <- fa_out_dist %>% 
  mutate(fa_scores = map(fa_scores, add_column)) %>% 
  mutate(norm_scores = map2(scores, fa_scores, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_scores) %>% 
  pull(norm_scores) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Scores",
                         Simulation = "Distinct",
                         Standardized = "No") %>% 
  select(Norm, Simulation, Standardized, everything())

fa_over_pred <- fa_out_over %>%
  mutate(norm_all = map2(sim, pred, function(x, y) {norm(as.matrix(x) - as.matrix(y), "F")/norm(as.matrix(x), "F")})) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Prediction",
                         Simulation = "Overlapping",
                         Standardized = "No") %>% 
  select(Norm, Simulation, Standardized, everything())

fa_over_load <- fa_out_over %>% 
  mutate(norm_loadings = map2(patterns, loadings, 
                              ~norm(as.matrix(.x) - as.matrix(t(.y)), "F") /
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_loadings) %>% 
  pull(norm_loadings) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Loadings",
                         Simulation = "Overlapping",
                         Standardized = "No") %>% 
  select(Norm, Simulation, Standardized, everything())

fa_over_score <- fa_out_over %>% 
  mutate(norm_scores = map2(scores, fa_scores, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_scores) %>% 
  pull(norm_scores) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Scores",
                         Simulation = "Overlapping",
                         Standardized = "No") %>% 
  select(Norm, Simulation, Standardized, everything())

fa_cor_pred <- fa_out_cor %>%
  mutate(norm_all = map2(sim, pred, function(x, y) {norm(as.matrix(x) - as.matrix(y), "F")/norm(as.matrix(x), "F")})) %>% 
  unnest(norm_all) %>% 
  pull(norm_all) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Prediction",
                         Simulation = "Correlated",
                         Standardized = "No") %>% 
  select(Norm, Simulation, Standardized, everything())

fa_cor_load <- fa_out_cor %>% 
  mutate(norm_loadings = map2(patterns, loadings, 
                              ~norm(as.matrix(.x) - as.matrix(t(.y)), "F") /
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_loadings) %>% 
  pull(norm_loadings) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Loadings",
                         Simulation = "Correlated",
                         Standardized = "No") %>% 
  select(Norm, Simulation, Standardized, everything())

fa_cor_score <- fa_out_cor %>% 
  mutate(norm_scores = map2(scores, fa_scores, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F")/norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_scores) %>% 
  pull(norm_scores) %>% summary() %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Scores",
                         Simulation = "Correlated",
                         Standardized = "No") %>% 
  select(Norm, Simulation, Standardized, everything())

rbind(fa_dist_pred,
      fa_over_pred,
      fa_cor_pred,
      fa_dist_load,
      fa_over_load,
      fa_cor_load,
      fa_dist_score, 
      fa_over_score,
      fa_cor_score) %>% 
  mutate_if(is.numeric, round, 2) %>% knitr::kable()
```

#### Standardized

Divide loadings by sum. Multiply scores by sum of associated loading.

```{r, fa9}
add_column <- function(score) {
  
  if (ncol(score) == 3) {
  score <- cbind(score, four = rep(0, times = nrow(score))) %>% as_tibble(.)
  } else if (ncol(score) == 2) {
  score <- cbind(score, three = rep(0, times = nrow(score)), four = rep(0, times = nrow(score))) %>% as_tibble(.)
  } else {}
  score
}

add_row <- function(pattern) {
  
  if (nrow(pattern) == 3) {
  pattern <- rbind(pattern, four = rep(0, times = ncol(pattern))) %>% as_tibble(.)
  } else if (nrow(pattern) == 2) {
  pattern <- rbind(pattern, three = rep(0, times = ncol(pattern)), four = rep(0, times = ncol(pattern))) %>% as_tibble(.)
  } else {}
  pattern
}

add_pattern <- function(pattern, true) {
  
  if (nrow(pattern) == 5) {
  true <- rbind(true, four = rep(0, times = ncol(true))) %>% as_tibble(.)
  } else if (nrow(pattern) == 6) {
  true <- rbind(true, three = rep(0, times = ncol(true)), four = rep(0, times = ncol(true))) %>% as_tibble(.)
  } else {}
  true
}

add_score <- function(score, true) {
  
  if (ncol(score) == 5) {
  true <- cbind(true, four = rep(0, times = nrow(true))) %>% as_tibble(.)
  } else if (ncol(score) == 6) {
  true <- cbind(true, three = rep(0, times = nrow(true)), four = rep(0, times = nrow(true))) %>% as_tibble(.)
  } else {}
  true
}

standard <- function(row_matrix, column_matrix) {
  sum_row <- apply(row_matrix, 1, function(x) sum(x))
  row_out <-  as_tibble(apply(row_matrix, 1, function(x) x/sum(x))) # Divide patterns by pattern sum to normalize
  col_out <- map2_dfr(as_tibble(column_matrix), sum_row, function(x,y) x*y) # multiply scores by pattern sum
  list(row_out = row_out, col_out = col_out)
}

fa_sd_dist_out <- fa_out_dist %>% 
  select(-sim, -noise, -pred, -chem, -fa_out) %>% 
  mutate(sd_patterns = map2(patterns, scores, function(x,y) standard(x,y)[[1]]),
         sd_scores   = map2(patterns, scores, function(x,y) standard(x,y)[[2]]),
         sd_fa_score       = map2(loadings, fa_scores,function(x,y) standard(t(x),y)[[2]]),
         sd_loading     = map2(loadings, fa_scores, function(x,y) standard(t(x),y)[[1]])) %>% 
  mutate(sd_patterns = map2(sd_loading, sd_patterns, add_pattern),
         sd_scores   = map2(sd_fa_score, sd_scores, add_score),
         sd_loading     = map(sd_loading, add_row),
         sd_fa_score    = map(sd_fa_score, add_column)) %>%
  select(-scores, -patterns, -loadings, -fa_scores)

fa_dist_norm <- fa_sd_dist_out %>% 
mutate(norm_eh = map2(sd_patterns, sd_loading, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_eh) %>% 
  pull(norm_eh)

fa_sd_over_out <- fa_out_over %>% 
  select(-sim, -noise, -pred, -chem, -fa_out) %>% 
  mutate(sd_patterns = map2(patterns, scores, function(x,y) standard(x,y)[[1]]),
         sd_scores   = map2(patterns, scores, function(x,y) standard(x,y)[[2]]),
         sd_fa_score       = map2(loadings, fa_scores,function(x,y) standard(t(x),y)[[2]]),
         sd_loading     = map2(loadings, fa_scores, function(x,y) standard(t(x),y)[[1]])) %>% 
  mutate(sd_patterns = map2(sd_loading, sd_patterns, add_pattern),
         sd_scores   = map2(sd_fa_score, sd_scores, add_score),
         sd_loading     = map(sd_loading, add_row),
         sd_fa_score    = map(sd_fa_score, add_column)) %>%
  select(-scores, -patterns, -loadings, -fa_scores)

fa_over_norm <- fa_sd_over_out %>%   
mutate(norm_eh = map2(sd_patterns, sd_loading, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_eh) %>% 
  pull(norm_eh)

fa_sd_cor_out <- fa_out_cor %>% 
  select(-sim, -noise, -pred, -chem, -fa_out) %>% 
  mutate(sd_patterns = map2(patterns, scores, function(x,y) standard(x,y)[[1]]),
         sd_scores   = map2(patterns, scores, function(x,y) standard(x,y)[[2]]),
         sd_fa_score       = map2(loadings, fa_scores,function(x,y) standard(t(x),y)[[2]]),
         sd_loading     = map2(loadings, fa_scores, function(x,y) standard(t(x),y)[[1]])) %>% 
  mutate(sd_patterns = map2(sd_loading, sd_patterns, add_pattern),
         sd_scores   = map2(sd_fa_score, sd_scores, add_score),
         sd_loading     = map(sd_loading, add_row),
         sd_fa_score    = map(sd_fa_score, add_column)) %>%
  select(-scores, -patterns, -loadings, -fa_scores)
  
fa_cor_norm <- fa_sd_cor_out %>%   
mutate(norm_eh = map2(sd_patterns, sd_loading, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_eh) %>% 
  pull(norm_eh)

dist_norm_fa_score <- fa_sd_dist_out %>% 
mutate(norm_fa_score = map2(sd_scores, sd_fa_score, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_fa_score) %>% 
  pull(norm_fa_score)

over_norm_fa_score <- fa_sd_over_out %>%   
mutate(norm_fa_score = map2(sd_scores, sd_fa_score, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_fa_score) %>% 
  pull(norm_fa_score)

cor_norm_fa_score <- fa_sd_cor_out %>%   
mutate(norm_fa_score = map2(sd_scores, sd_fa_score, 
                              ~norm(as.matrix(.x) - as.matrix(.y), "F") / 
                                norm(as.matrix(.x), "F"))) %>% 
  unnest(norm_fa_score) %>% 
  pull(norm_fa_score)

fa_over_load_s <- summary(fa_over_norm) %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Loadings",
                         Simulation = "Overlapping",
                         Standardized = "Yes") %>% 
  select(Norm, Simulation, Standardized, everything())

fa_cor_load_s <- summary(fa_cor_norm) %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Loadings",
                         Simulation = "Correlated",
                         Standardized = "Yes") %>% 
  select(Norm, Simulation, Standardized, everything())

fa_dist_load_s <- summary(fa_dist_norm) %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Loadings",
                         Simulation = "Distinct",
                         Standardized = "Yes") %>% 
  select(Norm, Simulation, Standardized, everything())

fa_over_score_s <- summary(over_norm_fa_score) %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Scores",
                         Simulation = "Overlapping",
                         Standardized = "Yes") %>% 
  select(Norm, Simulation, Standardized, everything())

fa_cor_score_s <- summary(cor_norm_fa_score) %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Scores",
                         Simulation = "Correlated",
                         Standardized = "Yes") %>% 
  select(Norm, Simulation, Standardized, everything())

fa_dist_score_s <- summary(dist_norm_fa_score) %>% as.matrix() %>% t() %>% 
  as_tibble() %>% mutate(Norm = "Scores",
                         Simulation = "Distinct",
                         Standardized = "Yes") %>% 
  select(Norm, Simulation, Standardized, everything())

rbind(fa_dist_load_s,
      fa_over_load_s,
      fa_cor_load_s,
      fa_dist_score_s, 
      fa_over_score_s,
      fa_cor_score_s) %>% 
  mutate_if(is.numeric, round, 2) %>% knitr::kable()
```

