---
title: "Poisson NMF & Sim Data -- Iterate"
author: "Lizzy Gibson"
date: "2/27/2020"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    code_folding: hide
---

```{r setup, include=FALSE}
options(scipen = 999)
library(MNdata) # my data
library(reshape2) # melt
library(gridExtra) # gridarrange
library(bindata) # multivariate binomial dist
library(NMF) # rmatrix
library(MASS) # mvrnorm
library(tidyverse)
library(R.matlab)
```

## Load Sims

```{r, load, cache = TRUE}
load(here::here("./Sims/Iterate/sim_dist.RDA"))

load(here::here("./Sims/Iterate/sim_cor.RDA"))

load(here::here("./Sims/Iterate/sim_over.RDA"))
```

## Distinct Patterns

```{r, long1, cache = TRUE}
get_nmf_div <- function (sim) {
  set.seed(1988)
  nmf_3 <- nmf(sim, 3, nrun = 100, method = "brunet")
  nmf_4 <- nmf(sim, 4, nrun = 100, method = "brunet")
  nmf_5 <- nmf(sim, 5, nrun = 100, method = "brunet")
  
  # aic_3 <- residuals(nmf_3) + (nrow(sim) + ncol(sim)) * 3
  # aic_4 <- residuals(nmf_4) + (nrow(sim) + ncol(sim)) * 4
  # aic_5 <- residuals(nmf_5) + (nrow(sim) + ncol(sim)) * 5
  bic_3 <- residuals(nmf_3) + (1/2)*(nrow(sim) + ncol(sim)) * 3 * log(nrow(sim) * ncol(sim))
  bic_4 <- residuals(nmf_4) + (1/2)*(nrow(sim) + ncol(sim)) * 4 * log(nrow(sim) * ncol(sim))
  bic_5 <- residuals(nmf_5) + (1/2)*(nrow(sim) + ncol(sim)) * 5 * log(nrow(sim) * ncol(sim))
  
 if (bic_3 <= bic_4) {
    nmf_out <- nmf_3
  } else if (bic_4 < bic_3 &&
             bic_4 <= bic_5) {
    nmf_out <- nmf_4
  } else {nmf_out <- nmf_5}
  
  basis <- as_tibble(basis(nmf_out))
  coef <- as_tibble(coef(nmf_out))
  pred <- basis(nmf_out) %*% coef(nmf_out)
  list(basis = basis, coef = coef, pred = pred)
  }

nmf_out_dist <- sim_dist %>%
  mutate(nmf_out = map(sim, get_nmf_div),
        coef = map(nmf_out, function(x) {x[[2]]}),
         pred = map(nmf_out, function(x) {x[[3]]}),
         basis = map(nmf_out, function(x) {x[[1]]})) %>% 
  select(-chem)

nmf_coef_dist <- nmf_out_dist %>% select(seed, coef) %>% unnest(cols = c(coef))
```

### Match & Arrange

```{r, nmf2, cache=TRUE}
match_patterns_corr <- function (truth, loading) {
  truth <- t(truth)
  if (nrow(truth) != nrow(loading)) {loading <- t(as.matrix(loading))} else {loading <- as.matrix(loading)}
  
  corr <- cor(truth, loading)
  
  reordered <- matrix(nrow = ncol(truth) - 1, ncol = nrow(truth))
  
  reordered[1,] <- loading[,which(corr==max(corr[1,]), arr.ind = TRUE)[2]]
  reordered[2,] <- loading[,which(corr==max(corr[2,]), arr.ind = TRUE)[2]]
  reordered[3,] <- loading[,which(corr==max(corr[3,]), arr.ind = TRUE)[2]]
  
  if (ncol(loading) >= 4) {reordered <- rbind(reordered, loading[,which(corr==max(corr[4,]), arr.ind = TRUE)[2]])}
  
  if (ncol(loading) == 5) {
  
  no <- c(which(corr==max(corr[1,]), arr.ind = TRUE)[2],
          which(corr==max(corr[2,]), arr.ind = TRUE)[2],
          which(corr==max(corr[3,]), arr.ind = TRUE)[2],
          which(corr==max(corr[4,]), arr.ind = TRUE)[2])
  
  reordered <- rbind(reordered, loading[,-no])
  }
  reordered
}

match_scores_nmf <- function (patterns, scores) {
  N <- nrow(scores)
  for (j in 1:nrow(patterns)) {
    for (i in 1:ncol(scores)) {
      if (patterns[j, 2] == j && scores[1, i] == j) {
        scores[(N+1), i] = patterns[j, 1]
      }
    }
  } 
  scores <- scores[c(1, nrow(scores), 2:(nrow(scores) - 1)),]
  scores
}

nmf_scores_matched_dist <- nmf_out_dist %>% 
    mutate(coef_reordered = map2(patterns, coef, function(x,y) match_patterns_corr(truth = x, loading = y)),
         basis_reordered = map2(coef_reordered, basis, ~match_scores_nmf(patterns = .x, scores = .y)))
```

### Viz

```{r, viz1, cache = TRUE}
nmf_coef_dist %>%
  filter(seed == 1) %>%
  mutate(pattern = 1:n()) %>% 
  select(seed, pattern, everything()) %>%
  gather(key = Chemicals, value = coefs, -pattern, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>%
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>%
  ggplot(aes(x = Chemicals, y = coefs)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~pattern) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

nmf_scores_matched_dist %>% 
  select(seed, coef_reordered) %>%
  mutate(coef_reordered = map(coef_reordered, as.tibble)) %>% 
  unnest(cols = coef_reordered) %>% 
  group_by(seed) %>% 
  mutate(pattern = 1:n()) %>%
  gather(key = Chemicals, value = coefs, -pattern, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = coefs)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = .45, outlier.shape = NA) +
  facet_wrap(.~pattern) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

## Overlapping Patterns

```{r, over, cache = TRUE}
nmf_out_over <- sim_over %>% 
    mutate(nmf_out = map(sim, get_nmf_div),
        coef = map(nmf_out, function(x) {x[[2]]}),
         pred = map(nmf_out, function(x) {x[[3]]}),
         basis = map(nmf_out, function(x) {x[[1]]})) %>% 
  select(-chem)

nmf_coef_over <- nmf_out_over %>% select(seed, coef) %>% unnest(cols = c(coef))
```

### Match & Arrange

```{r, nmf5, cache=TRUE}
nmf_scores_matched_over <- nmf_out_over %>% 
    mutate(coef_reordered = map2(patterns, coef, function(x,y) match_patterns_corr(truth = x, loading = y)),
           basis_reordered = map2(coef_reordered, basis, function(x,y) match_scores_nmf(patterns = x, scores = y)))
```

### Viz

```{r, viz2, cache = TRUE}
nmf_coef_over %>%  
  filter(seed == 1) %>%
  mutate(pattern = 1:n()) %>% 
  select(seed, pattern, everything()) %>% 
  gather(key = Chemicals, value = coefs, -pattern, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = coefs)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~pattern) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

nmf_scores_matched_over %>% 
  select(seed, coef_reordered) %>%
  mutate(coef_reordered = map(coef_reordered, as.tibble)) %>% 
  unnest(cols = coef_reordered) %>% 
  group_by(seed) %>% 
  mutate(pattern = 1:n()) %>% 
  gather(key = Chemicals, value = coefs, -pattern, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = coefs)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = .45, outlier.shape = NA) +
  facet_wrap(.~pattern) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

## Correlated Scores

```{r, corr, cache = TRUE}
nmf_out_cor <- sim_cor %>% 
    mutate(nmf_out = map(sim, get_nmf_div),
        coef = map(nmf_out, function(x) {x[[2]]}),
         pred = map(nmf_out, function(x) {x[[3]]}),
         basis = map(nmf_out, function(x) {x[[1]]})) %>% 
  select(-chem)

nmf_coef_cor <- nmf_out_cor %>% select(seed, coef) %>% unnest(cols = c(coef))
```

### Match & Arrange

```{r, nmf8, cache = TRUE}
nmf_scores_matched_cor <- nmf_out_cor %>% 
    mutate(coef_reordered = map2(patterns, coef, function(x,y) match_patterns_corr(truth = x, loading = y)),
         basis_reordered = map2(coef_reordered, basis, function(x,y) match_scores_nmf(patterns = x, scores = y)))
```

### Viz

```{r, viz3, cache = TRUE}
nmf_coef_cor %>%  
  filter(seed == 1) %>%
  mutate(pattern = 1:n()) %>% 
  select(seed, pattern, everything()) %>% 
  gather(key = Chemicals, value = coefs, -pattern, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Chemicals, y = coefs)) + geom_col(aes(fill = Group)) +
  facet_wrap(.~pattern) + theme_bw() +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

nmf_scores_matched_cor %>%  
  select(seed, coef_reordered) %>%
  mutate(coef_reordered = map(coef_reordered, as.tibble)) %>% 
  unnest(cols = coef_reordered) %>% 
  group_by(seed) %>% 
  mutate(pattern = 1:n()) %>% 
  gather(key = Chemicals, value = coefs, -pattern, -seed) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>% 
  mutate(Group = ifelse(str_detect(Chemicals, "BDE"), "PBDEs",
                                                     ifelse(str_detect(Chemicals, "^M"), "Phthalates",
                                                            ifelse(str_detect(Chemicals, "pcb"), "PCBs",
                                                                   "Phenols")))) %>% 
  ggplot(aes(x = Group, y = coefs)) + geom_jitter(aes(color = Group), alpha = 0.5, size = 0.1, height = 0) +
  geom_boxplot(aes(x = Group, color = Group), width = .45, outlier.shape = NA) +
  facet_wrap(.~pattern) + theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank())
```

## Summarize

### Rank

```{r}
rank_d <- nmf_out_dist %>% 
  mutate(rank = map(coef, nrow)) %>% 
  select(rank) %>%
  unnest(rank) %>%
  group_by(rank) %>%
  summarise(n = n()) %>%
  mutate(Simulation = "Distinct") %>%
  mutate(Proportion = n/100) %>%
  select(Simulation, Rank = rank, Proportion)

rank_o <- nmf_out_over %>% 
  mutate(rank = map(coef, nrow)) %>%
  select(rank) %>%
  unnest(rank) %>%
  group_by(rank) %>%
  summarise(n = n()) %>%
  mutate(Simulation = "Overlapping") %>%
  mutate(Proportion = n/100) %>%
  select(Simulation, Rank = rank, Proportion)

rank_c <- nmf_out_cor %>% 
  mutate(rank = map(coef, nrow)) %>%
  select(rank = rank) %>%
  unnest(rank) %>%
  group_by(rank) %>%
  summarise(n = n()) %>%
  mutate(Simulation = "Correlated") %>%
  mutate(Proportion = n/100) %>%
  select(Simulation, Rank = rank, Proportion)


rbind(rank_d, rank_o, rank_c) %>% knitr::kable()
```

