---
title: "npBNMF -- Standardized & Not"
author: "Lizzy Gibson"
date: "7/20/2020"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: 'hide'
---

```{r setup, include=FALSE}
options(scipen = 999)
library(MNdata) # my data
library(reshape2) # melt
library(gridExtra) # gridarrange
library(bindata) # multivariate binomial dist
library(NMF) # rmatrix
library(MASS) # mvrnorm
library(tidyverse)
library(R.matlab)
```

```{r, LOAD, cache = TRUE}
load("./HPC/Rout/dist_output_all_un.RDA")
load("./HPC/Rout/over_output_all_un.RDA")
load("./HPC/Rout/cor_output_all_un.RDA")
load("./HPC/Rout/all_unstand.RDA")
# all_unstand

load("./HPC/Rout/dist_output_all.RDA")
load("./HPC/Rout/over_output_all.RDA")
load("./HPC/Rout/cor_output_all.RDA")
load("./HPC/Rout/all_stand.RDA")
# all_stand
```

## Rank

### Unstandardized Sims

```{r}
all_unstand %>% 
  mutate(bnmf_rank = map(eh, nrow)) %>% 
  dplyr::select(seed, sim_type, fa_rank, pca_rank, nmf_l2_rank, nmf_p_rank, bnmf_rank) %>% 
  unnest(c(fa_rank, pca_rank, nmf_l2_rank, nmf_p_rank, bnmf_rank)) %>% 
  pivot_longer(cols = fa_rank:bnmf_rank) %>% 
  group_by(sim_type, name, value) %>% 
  summarise(n()) %>% knitr::kable()
```

### Standardized Sims

```{r}
all_stand %>% 
  mutate(bnmf_rank = map(eh, nrow)) %>% 
  dplyr::select(seed, sim_type, fa_rank, pca_rank, nmf_l2_rank, nmf_p_rank, bnmf_rank) %>% 
  unnest(c(fa_rank, pca_rank, nmf_l2_rank, nmf_p_rank, bnmf_rank)) %>% 
  pivot_longer(cols = fa_rank:bnmf_rank) %>% 
  group_by(sim_type, name, value) %>% 
  summarise(n()) %>% knitr::kable()
```

## Relative Prediction Error

### Unstandardized Sims
```{r}
all_unstand_error <- all_unstand %>% dplyr::select(seed, sim_type, sim, grep("pred", colnames(.))) %>% 
  pivot_longer(pca_pred:bnmf_pred) %>% 
  mutate(l2 = map2(sim, value, function (x,y) norm(x-y, "F")/norm(x, "F"))) %>% 
  dplyr::select(seed, sim_type, name, l2) %>% 
  unnest(l2)

all_unstand_error %>% 
  ggplot(aes(x = name, y = l2)) +
  geom_boxplot() +
  facet_grid(~sim_type) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(title = "Relative Predictive Error on Unstandardized Sims")
```

### Standardized Sims
```{r}
all_stand_error <- all_stand %>% dplyr::select(seed, sim_type, sim, grep("pred", colnames(.))) %>% 
  pivot_longer(pca_pred:bnmf_pred) %>% 
  mutate(l2 = map2(sim, value, function (x,y) norm(x-y, "F")/norm(x, "F"))) %>% 
  dplyr::select(seed, sim_type, name, l2) %>% 
  unnest(l2)

all_stand_error %>% 
  ggplot(aes(x = name, y = l2)) +
  geom_boxplot() +
  facet_grid(~sim_type) + 
  geom_vline(xintercept = 0, color = "pink", linetype = "dashed", size = 0.5) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(title = "Relative Predictive Error on Standardized Sims")
```

### L1 Error
```{r}
all_unstand %>% dplyr::select(seed, sim_type, sim, grep("pred", colnames(.))) %>% 
  pivot_longer(pca_pred:bnmf_pred) %>% 
  mutate(l1 = map2(sim, value, function (x,y) sum(abs(x-y))/sum(abs(x)))) %>% 
  dplyr::select(seed, sim_type, name, l1) %>% 
  unnest(l1) %>% 
  ggplot(aes(x = name, y = l1)) +
  geom_boxplot() +
  facet_grid(~sim_type) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(title = "Relative L1 Error on Unstandardized Sims")
```

```{r}
all_stand %>% dplyr::select(seed, sim_type, sim, grep("pred", colnames(.))) %>% 
  pivot_longer(pca_pred:bnmf_pred) %>% 
  mutate(l1 = map2(sim, value, function (x,y) sum(abs(x-y))/sum(abs(x)))) %>% 
  dplyr::select(seed, sim_type, name, l1) %>% 
  unnest(l1) %>% 
  ggplot(aes(x = name, y = l1)) +
  geom_boxplot() +
  facet_grid(~sim_type) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(title = "Relative L1 Error on Unstandardized Sims")
```

## Symmetric Subspace Distance

### Unstandardized Sims
```{r}
all_unstand_ssdist <- all_unstand %>% dplyr::select(seed, sim_type, grep("_ssdist", colnames(.))) %>% 
  unnest(cols = c(pca_rotation_ssdist, pca_scores_ssdist, fa_rotations_ssdist, 
                  fa_scores_ssdist, nmf_l2_loading_ssdist, nmf_l2_scores_ssdist, 
                  nmf_p_loading_ssdist, nmf_p_scores_ssdist,
                  bnmf_scores_ssdist, bnmf_loading_ssdist)) %>% 
  pivot_longer(grep("_ssdist", colnames(.)),
               names_to = "type",
               values_to = "value") %>%
  mutate(model = str_sub(type, 1, 6),
         model = ifelse(str_detect(model, 'pca'), 'pca', model),
         model = ifelse(str_detect(model, 'l2'), 'nmf_l2', model),
         model = ifelse(str_detect(model, 'fa'), 'fa', model),
         model = ifelse(str_detect(model, '_p_'), 'nmf_p', model),
         model = ifelse(str_detect(model, 'bnmf'), 'bnmf', model),
         type = ifelse(str_detect(type, 'scores'), 'scores', "loadings")) 

all_unstand_ssdist %>% 
  ggplot(aes(x = model, y = value)) +
  geom_boxplot() +
  facet_grid(sim_type~type) + 
  geom_hline(yintercept = 0.5, color = "pink", linetype = "dashed") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none") + 
  labs(title = "Symmetric Subspace Distance on Unstandardized Sims")
```

### Standardized Sims
```{r}
all_stand_ssdist <- all_stand %>% dplyr::select(seed, sim_type, grep("_ssdist", colnames(.))) %>% 
  unnest(cols = c(pca_rotation_ssdist, pca_scores_ssdist, fa_rotations_ssdist, 
                  fa_scores_ssdist, nmf_l2_loading_ssdist, nmf_l2_scores_ssdist, 
                  nmf_p_loading_ssdist, nmf_p_scores_ssdist,
                  bnmf_scores_ssdist, bnmf_loading_ssdist)) %>% 
  pivot_longer(grep("_ssdist", colnames(.)),
               names_to = "type",
               values_to = "value") %>%
  mutate(model = str_sub(type, 1, 6),
         model = ifelse(str_detect(model, 'pca'), 'pca', model),
         model = ifelse(str_detect(model, 'l2'), 'nmf_l2', model),
         model = ifelse(str_detect(model, 'fa'), 'fa', model),
         model = ifelse(str_detect(model, '_p_'), 'nmf_p', model),
         model = ifelse(str_detect(model, 'bnmf'), 'bnmf', model),
         type = ifelse(str_detect(type, 'scores'), 'scores', "loadings")) 

all_stand_ssdist %>% 
  ggplot(aes(x = model, y = value)) +
  geom_boxplot(varwidth = TRUE) +
  facet_grid(sim_type~type) + 
  geom_hline(yintercept = 0.5, color = "pink", linetype = "dashed") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none") + 
  labs(title = "Symmetric Subspace Distance on Standardized Sims")
```

### Histograms
```{r}
all_unstand_ssdist %>% 
  ggplot(aes(x = value)) +
  geom_histogram(aes(fill = sim_type), bins = 100, alpha = 0.75) +
  facet_grid(type ~ model) + 
  geom_vline(xintercept = 0.5, color = "pink", linetype = "dashed", size = 0.5) +
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(title = "Symmetric Subspace Distance on Unstandardized Sims")

all_stand_ssdist %>% 
  ggplot(aes(x = value)) +
  geom_histogram(aes(fill = sim_type), bins = 100, alpha = 0.75) +
  facet_grid(type ~ model) + 
  geom_vline(xintercept = 0.5, color = "pink", linetype = "dashed", size = 0.5) +
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(title = "Symmetric Subspace Distance on Standardized Sims")
```

